### ISSUE TITLE
Cutadapt hangs when encountering improperly paired input read1 and read2 fastq

### ISSUE THREAD

**Issue by obenno** [marcelm/cutadapt#581] opened 2021-11-26 13:36 UTC
Hi,

Thanks for developing such a good tool, please kindly find some info below:

- Cutadapt was installed via `conda install cutadpt`, and the version is `3.5`, with python verison: `3.9.7`
- cutadapt hangs with:
```
This is cutadapt 3.5 with Python 3.9.7
Command line parameters: -a A{20} -j 4 -o R1.trimmed.fq.gz -p R2.trimmed.fq.gz tmp.R1.fq.gz tmp.R2.fastq.gz
Processing reads on 4 cores in paired-end mode ...
ERROR: Traceback (most recent call last):
  File "/home/xzx/Tools/miniconda3/envs/cutadapt/lib/python3.9/site-packages/cutadapt/pipeline.py", line 646, in run
    (n, bp1, bp2) = self._pipeline.process_reads()
  File "/home/xzx/Tools/miniconda3/envs/cutadapt/lib/python3.9/site-packages/cutadapt/pipeline.py", line 438, in process_reads
    for read1, read2 in self._reader:
  File "/home/xzx/Tools/miniconda3/envs/cutadapt/lib/python3.9/site-packages/dnaio/pairedend.py", line 76, in __iter__
    raise FileFormatError(
dnaio.exceptions.FileFormatError: Error in sequence file at unknown line: Reads are improperly paired. Read name 'HISEQ_HU0' in file 1 does not match 'HISEQ_HU01:89:H7YRLADXX:1:1101:1129:2182 2:N:0:ATCACG' in file 2.
```
- Expected behavior: the program will exit with exit code

How to reproduce the error:
The command works well with single thread:
```
cutadapt -a "A{20}" -o R1.trimmed.fq.gz -p R2.trimmed.fq.gz test.R1.fq.gz test.R2.fq.gz
```
but will hang with `-j` option:
```
cutadapt -a "A{20}" -j 2 -o R1.trimmed.fq.gz -p R2.trimmed.fq.gz test.R1.fq.gz test.R2.fq.gz
```

[test.R2.fq.gz](https://github.com/marcelm/cutadapt/files/7609013/test.R2.fq.gz)
[test.R1.fq.gz](https://github.com/marcelm/cutadapt/files/7609014/test.R1.fq.gz)

**Comment by marcelm** [comment] 2021-11-26 16:04
Thanks for reporting. I admit it’s maybe a bit hard to find, but this is actually a duplicate of #528. I will take this additional report as some extra motivation to finally get this fixed. It requires some redesign of the multicore code, which isn’t easy, and the last time I tried it, it actually made things worse.

**Closed by marcelm** 2021-11-26 16:04 UTC
