### ISSUE TITLE
Invalid paired-end output

### ISSUE THREAD

**Issue by bnorthoff** [marcelm/cutadapt#365] opened 2019-03-08 13:25 UTC
Hi Marcel, I am using cutadapt version 1.18 installed by pip (python 2.7.14) to preprocess my paired-end data. This morning I have some trouble due to an unexpected end of fastq-files generated by cutadapt.

Using the command cutadapt --nextseq-trim=15  -a AGATCGGAAGAGC -A AGATCGGAAGAGC  --output $read1trimmed 	--paired-output $read2trimmed --minimum-length=20 --pair-filter=any $read1raw $read2raw > $trimmedlog I am getting truncated files in some cases.
Here I am using variables instead of filenames within a loop.

Due to an error given by FASTQC, I have checked the length of the trimmed files by hand:
zcat AmP1_R1.trimmed.fastq.gz | wc -l
33124228

zcat AmP1_R2.trimmed.fastq.gz | wc -l
gzip: AmP1_R2.trimmed.fastq.gz: unexpected end of file
33121587

Furthermore, I have checked the last entry in the corrupted file:
zcat AmP1_R2.trimmed.fastq.gz | tail -n 20
gzip: AmP1_R2.trimmed.fastq.gz: unexpected end of file
@NBxxxx
ATTTCATTCCATTCCATTCCATTCCATTTCATTCCATTCCGTTCCACTCCATTCCATTCTATTCAATTCCATTCCAT
+
AAAAAEEEEEEAEEEEEEEA/EEEEEEEEEAEEEEEEE<E

Both corresponding input files give the same number of lines and can be analyzed by FASTQC, indicating that there is no problem. Furthermore, only a subset of my files are affected.

Dou you have any suggestions?

**Comment by marcelm** [comment] 2019-03-08 14:00
Hi, I strongly suspect that the problem is not with Cutadapt in this case. An incomplete output file often points to a full disk or that a quota was reached. It could also mean that Cutadapt was interrupted for some other reason.

Do you have the standard error output still available? You redirected only stdout to a file, but error messages would go to stderr (you would need `... > $trimmedlog 2> $trimmederrorlog` to capture it). Any "disk full" messages would have been printed there. On the other hand, if the report in the $trimmedlog looks fine, then the FASTQ output should also be complete.

In your script, I strongly suggest that you add `set -euo pipefail` just after `#!/bin/bash` (some people call this ["bash strict mode"](http://redsymbol.net/articles/unofficial-bash-strict-mode/) if you haven’t done so, yet. The `set -e` is the important part here: Without it, your script continues running even if one of the commands fails (that is, exits with a nonzero error code), which can mask lots of bugs.

**Comment by bnorthoff** [comment] 2019-03-11 12:07
This morning I've updated to cutadapt 2.0 (using Python 3.6.5, pip 19.0.3, SLE 15) due to the possibility to use multiple cores with python 3.
After problems installing xopen for python3 (https://github.com/marcelm/xopen/issues/10), cutadapt gets still interrupted without any error messages  in stderr. The last entry in Stdout is "Processing reads on 104 cores in paired-end mode ..."

**Comment by marcelm** [comment] 2019-03-11 12:23
Can you please retry with a lower number of threads? Not higher than 16 or 20 for the moment. If you go higher, the overhead for communication between processes probably overwhelms any gains in speed, so it could actually become slower.

If you can, run your command only on a single dataset without redirecting anything (stdout/stderr). Cutadapt 2 has a progress indicator, is that shown?

You haven’t replied to my earlier comment.

**Comment by bnorthoff** [comment] 2019-03-11 13:39
Hi Marcel, thank's a lot for you support!

Concerning your earlier comment: I did not use "set -euo pipefail". Thank's a lot for this hint! The stdout of the previous analysis ended with
`Processing reads on 1 core in paired-end mode ...`
and the stderr was not saved.

Concerning you last comment: I rerun the analysis as suggested (without loop):
`./test.cutadapt.sh
This is cutadapt 2.0 with Python 3.6.5
Command line parameters: --nextseq-trim=20 --minimum-length 20 --cores=16 -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCA -A AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT --output AmP1_R1.trimmed.fastq.gz --paired-output AmP1_R2.trimmed.fastq.gz AmP1_R1.fastq.gz AmP1_R2.fastq.gz
Processing reads on 16 cores in paired-end mode ...
[          8<] 00:04:22   22,245,481 reads   @       13 us/read;    4.64 M reads/minute`
The progress indicator was shown until the process got interrupted. There was also no final summary.

I have also repeated this analysis with saving stdout and stderr. The stdout ended again with the entry
`Processing reads on 16 cores in paired-end mode ...`
and the stdout was empty.

**Comment by marcelm** [comment] 2019-03-11 13:55
What exactly do you mean by “until the process got interrupted”? Were there any messages? What was the exit code of the cutadapt command when you ran it interactively? That is, run cutadapt until it gets interrupted, then please run `echo $?` and let me know what it outputs.

Try the above first and then please also run the command again with `--cores=1` to disable multi-core support. Then we will know whether the problem is in that code.

**Comment by bnorthoff** [comment] 2019-03-11 14:18
When the preocess gets interrupted, there is no message or additional exit code (just the command line `user@server:directory>`). Running `echo $?` gives `1`. The same happens with one core. What do you mean with running it interactively?

**Comment by marcelm** [comment] 2019-03-11 14:41
With running interactively I mean running it directly from a command prompt, so not within a script. Just copy and paste the command into the commandline and press enter. I thought you did this above, but I see now that some script is involved (`test.cutadapt.sh`). Try not to use the script.

**Comment by bnorthoff** [comment] 2019-03-11 14:57
Running the command directly in the command lines ends with the results (for using 16 cores and 1 core):

`cutadapt --nextseq-trim=20 --minimum-length 20 --cores=1 -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCA -A AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT --output AmP1_R1.trimmed.fastq.gz --paired-output AmP1_R2.trimmed.fastq.gz AmP1_R1.fastq.gz AmP1_R2.fastq.gz
This is cutadapt 2.0 with Python 3.6.5
Command line parameters: --nextseq-trim=20 --minimum-length 20 --cores=1 -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCA -A AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT --output AmP1_R1.trimmed.fastq.gz --paired-output AmP1_R2.trimmed.fastq.gz AmP1_R1.fastq.gz AmP1_R2.fastq.gz
Processing reads on 1 core in paired-end mode ...
[--------=8  ] 00:03:33    3,200,000 reads   @       65 us/read;    0.92 M reads/minute`

`cutadapt --nextseq-trim=20 --minimum-length 20 --cores=16 -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCA -A AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT --output AmP1_R1.trimmed.fastq.gz --paired-output AmP1_R2.trimmed.fastq.gz AmP1_R1.fastq.gz AmP1_R2.fastq.gz
This is cutadapt 2.0 with Python 3.6.5
Command line parameters: --nextseq-trim=20 --minimum-length 20 --cores=16 -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCA -A AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT --output AmP1_R1.trimmed.fastq.gz --paired-output AmP1_R2.trimmed.fastq.gz AmP1_R1.fastq.gz AmP1_R2.fastq.gz
Processing reads on 16 cores in paired-end mode ...
[      8=----] 00:00:22    1,934,406 reads   @       11 us/read;    5.33 M reads/minute`

**Comment by marcelm** [comment] 2019-03-11 15:28
I would also like to know the exit code of the command when you run it directly on the command line. You need to run `echo $?` directly after the command has finished/was interrupted.

**Comment by marcelm** [comment] 2019-03-11 15:29
I suspected a full disk or a quota that has been reached. Have you checked this?

**Comment by bnorthoff** [comment] 2019-03-11 15:39
Concerning the exit code: The command `echo $?` just gave `1` :

`user@htseq:~/fastq>cutadapt --nextseq-trim=20 --minimum-length 20 --cores=1 -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCA -A AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT --output AmP1_R1.trimmed.fastq.gz --paired-output AmP1_R2.trimmed.fastq.gz AmP1_R1.fastq.gz AmP1_R2.fastq.gz
This is cutadapt 2.0 with Python 3.6.5
Command line parameters: --nextseq-trim=20 --minimum-length 20 --cores=1 -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCA -A AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT --output AmP1_R1.trimmed.fastq.gz --paired-output AmP1_R2.trimmed.fastq.gz AmP1_R1.fastq.gz AmP1_R2.fastq.gz
Processing reads on 1 core in paired-end mode ...
[--------=8  ] 00:03:33    3,200,000 reads   @       65 us/read;    0.92 M reads/minute
user@htseq:~/fastq> echo $?
1`

There is enough disk capacity and memory available. Are there other important quotas?

**Comment by marcelm** [comment] 2019-03-11 16:16
I don’t know what is going on to be honest. If there are any problems such as too little disk space, too little memory, a segmentation fault, the process being killed externally, then the exit code should not be 1, and at least a message should be printed.

Can you please check the input files with `zcat ... | wc -l`, as you did for the output files?

Can you please also remove all filtering and trimming options and see what that does? So only this:
```
cutadapt --output AmP1_R1.trimmed.fastq.gz --paired-output AmP1_R2.trimmed.fastq.gz AmP1_R1.fastq.gz AmP1_R2.fastq.gz
```

**Comment by bnorthoff** [comment] 2019-03-12 13:33
The lengtj of the input files is identical:

`zcat AmP1_R1.fastq.gz | wc -l
97733068`

`zcat AmP1_R2.fastq.gz | wc -l
97733068`

I also rerun the analysis withput any filtering and trimming options:

`user@htseq:~/fastq>cutadapt --output AmP1_R1.trimmed.fastq.gz --paired-output AmP1_R2.trimmed.fastq.gz AmP1_R1.fastq.gz AmP1_R2.fastq.gz
This is cutadapt 2.0 with Python 3.6.5
Command line parameters: --output AmP1_R1.trimmed.fastq.gz --paired-output AmP1_R2.trimmed.fastq.gz AmP1_R1.fastq.gz AmP1_R2.fastq.gz
Processing reads on 1 core in paired-end mode ...
user@htseq:~/fastq> echo $?
1`

The output is still invalid:

`zcat AmP1_R1.trimmed.fastq.gz | wc -l
56954128`

`zcat AmP1_R2.trimmed.fastq.gz | wc -l
gzip: AmP1_R2.trimmed.fastq.gz: unexpected end of file
56950441`

Additionally our administrator has checked the log-files of the server for unusual events. However he was also not able to find external influences at the time points of occurrence.

**Comment by marcelm** [comment] 2019-03-12 14:09
Thanks. Do you think you could make the input files available to me? Run `cutadapt --help|head` to see my e-mail address.

If not, can you try to run cutadapt on a different machine, such as a laptop? Use the same shortened command as above.

Also, what is the version of `xopen` that is installed? (Use `pip freeze | grep xopen` to find out).

**Comment by marcelm** [comment] 2019-03-13 13:02
Also please let me know if you don’t want to pursue this further, which is totally fine.

**Comment by MithrasXO** [comment] 2019-03-25 06:57
Hello Marcel, 
Bernd handed over the issue to me, because I'm a little bit more into Linux and stuff. I tried few things and can tell you:

1. The script does run fine on another machine (also a server but slightly older).
2. Strace says that there are a few packages missing for hardware acceleration (AVX 512), which it doesnt on the older machine
3. If I run the script with "--debug" flag it succedes (WTF?)
        cutadapt --debug \
	--nextseq-trim=20 --minimum-length 20 --cores=16 \
	-a AGATCGGAAGAGCACACGTCTGAACTCCAGTCA -A AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT \
	--output AmP1_R1.trimmed.fastq.gz --paired-output AmP1_R2.trimmed.fastq.gz \
 	AmP1_R1.fastq.gz AmP1_R2.fastq.gz)
4. I can give you the full Strace-Log if you want to

Thanks for you assistance!

**Comment by marcelm** [comment] 2019-03-25 15:09
Ok, thanks for the investigation. It appears that the error is a SIGPIPE that occurs when the main process writes the processed reads to the output file. To be precise: Cutadapt opens `gzip` or `pigz` child process and lets those handle the compression (this is faster than using Python’s built-in routines for writing compressed files). So file descriptor 9 should be a pipe to one of the child processes.

The SIGCHLD is sent when the child process is killed, and SIGPIPE is sent when the main process tries to send data to the pipe although the other end of the pipe is no longer connected.

Can you please check whether you see two `gzip` or `pigz` subprocesses while `cutadapt` is running? If `pigz` is running, which version is installed (check with `pigz -V`)?

When you do further experiments, please omit as many command-line options as possible while still getting the crash. (Bernd left out the trimming options and still got the crash.)

Can you do a couple of experiments to find out how complete the output file is when the crash occurs, and whether that varies from run to run? When I interpret the [comment above](https://github.com/marcelm/cutadapt/issues/365#issuecomment-472002106) correctly, then the input files have 97733068 lines, but the output had only around half of that. Can you verify?

One other possibility would be that the output file is “almost” complete, that is, only a couple of lines are missing. In that case, it could be that cutadapt somehow forgets to write the final data to the output before it exits.

**Comment by marcelm** [comment] 2019-03-25 15:11
One more idea: Assuming that your system does have `pigz` installed, can you try to run it manually on the two input files and see whether that runs successfully?
```
zcat AmP1_R1.fastq.gz | pigz -p 4 > out.fastq.gz
zcat AmP1_R2.fastq.gz | pigz -p 4 > out.fastq.gz
```

**Comment by MithrasXO** [comment] 2019-03-27 10:03
Hello Marcel,

here we go:

1. Even with just one Core I see around 8 subprocesses of `pigz ` running
2. Version: `pigz 2.3.3`
3. The crash occurs at random times while executing the script but for example: 
            Input file: `97733068 `
            Output file:  `58861820 (with warning: gzip: AmP1_R1.trimmed.fastq.gz: unexpected end of file)`
4. Running pigz with the commands stated above results in an error: `pigz: abort: internal threads error`. 

I will start to investigate this issue. 

Thanks!

**Comment by marcelm** [comment] 2019-03-27 10:27
Ok, so this appears to be a problem in pigz, and I’m admittedly somewhat glad to see that this is not a bug in Cutadapt itself.

My pigz version is 2.4, so perhaps a simple upgrade will solve the problem for you.

Cutadapt always runs pigz with four threads and disregards the number of cores specified on the commandline; this is issue #290. Since you write two output files, it is expected that there are eight pigz threads in total.

As a workaround, you can temporarily unset the `PATH` environment variable to prevent cutadapt from using external processes. Something like this should work:
```
$ which cutadapt
/.../path/to/cutadapt
$ PATH= /.../path/to/cutadapt ... -o out.fastq.gz in.fastq.gz
```
Note the space after `PATH=`.

I should perhaps make it configurable whether `pigz` is used at all, but the above should work in the meantime (it may be a bit slower, though).

**Comment by MithrasXO** [comment] 2019-03-27 10:47
I upgraded to 2.4 but the error is still there. I will try the other solution after lunch.

Thanks

**Comment by MithrasXO** [comment] 2019-03-27 12:57
Without pigz, it works like a charm, but it is really slow. I will check if some of the pgiz parameters can help to prevent the crash of pigz. Thanks

**Comment by marcelm** [comment] 2019-04-17 14:20
Since the problem is in pigz, I’ll close this issue now. As I mentioned above, it would probably be a good idea to have an option for disabling use of pigz, so these problems can be worked around, but I would consider that to be part of issue #290.

**Closed by marcelm** 2019-04-17 14:20 UTC
