### ISSUE TITLE
Error when quality trimming large files

### ISSUE THREAD

**Issue by markopetek** [marcelm/cutadapt#129] opened 2015-06-09 07:11 UTC
I got this error while trying to trim paired end fastq files:

    cutadapt -q 10 --minimum-length 20 -o ./cut/TN90_1_cut.fastq -p ./cut/TN90_2_cut.fastq ./fastq/TN90_1.fastq ./fastq/TN90_2.fastq
    Traceback (most recent call last):
      File "/usr/local/bin/cutadapt", line 10, in <module>
    cutadapt.main()
      File "/usr/local/lib/python2.7/dist-packages/cutadapt/scripts/cutadapt.py", line 821, in main
    stats = process_paired_reads(reader, modifiers, modifiers2, writers)
      File "/usr/local/lib/python2.7/dist-packages/cutadapt/scripts/cutadapt.py", line 319, in process_paired_reads
    if writer(read1, read2):
      File "/usr/local/lib/python2.7/dist-packages/cutadapt/writers.py", line 95, in __call__
    read2.write(self.untrimmed_paired_outfile)
      File "_seqio.pyx", line 93, in cutadapt._seqio.Sequence.write (cutadapt/_seqio.c:2406)
    IOError: [Errno 71] Protocol error

**Comment by marcelm** [comment] 2015-06-09 09:07
Hi, thanks for the report, but I think this is a problem with your system, not in cutadapt. Can you reproduce the error when you run the same command twice? I searched for the error message and it seems it can be caused by filesystem damage. Perhaps it also has to do something with a networking filesystem? Sorry about that, but I don’t think I can do much about it.

**Comment by markopetek** [comment] 2015-06-09 10:01
I concatenated the forward and reverse reads from 8 into 2 files and wanted to run cutadapt just once.  It seems like the 'cat' command didn't produce a valid fastq file, each of the two files was cca 400 Gb. 

I'll try to run cutadapt separately on original fastq files.

**Comment by marcelm** [comment] 2015-06-09 11:13
Running it separately also makes sense since you could then run it in parallel. Is it ok if I close this issue?

**Closed** 2015-06-09 20:16 UTC
