### ISSUE TITLE
Error when try to run cutadapt installed by conda: AttributeError: module 'zlib' has no attribute 'Z_RLE'

### ISSUE THREAD

**Issue by hero-outman** [marcelm/cutadapt#519] opened 2021-03-23 07:00 UTC
I installed cutadapt by `conda install -c bioconda cutadapt` on my centos7 machine , and when try to run cutadapt, throws error like this: 
```
Traceback (most recent call last):
  File "/home/myhome/.conda/envs/bioinfo/bin/cutadapt", line 7, in <module>
    from cutadapt.__main__ import main_cli
  File "/home/myhome/.conda/envs/bioinfo/lib/python3.6/site-packages/cutadapt/__main__.py", line 64, in <module>
    import dnaio
  File "/home/myhome/.conda/envs/bioinfo/lib/python3.6/site-packages/dnaio/__init__.py", line 31, in <module>
    from xopen import xopen
  File "/home/myhome/.conda/envs/bioinfo/lib/python3.6/site-packages/xopen/__init__.py", line 31, in <module>
    from isal import igzip, isal_zlib  # type: ignore
  File "/home/myhome/.conda/envs/bioinfo/lib/python3.6/site-packages/isal/igzip.py", line 30, in <module>
    from . import isal_zlib
  File "src/isal/isal_zlib.pyx", line 60, in init isal.isal_zlib
AttributeError: module 'zlib' has no attribute 'Z_RLE' 
```

I have isa-l and zlib in conda list, and googled for hours, can not find a solution. Please give me some advice.

**Comment by marcelm** [comment] 2021-03-26 10:56
Hi, I’m on vacation this week and will get back to you next week. In the meantime, you can try to install an older Cutadapt version: `conda install -c bioconda -c conda-forge cutadapt=3.2` (try 3.1 and 3.0 as well if that doesn’t work).

**Comment by marcelm** [comment] 2021-03-30 09:17
I cannot reproduce the problem unfortunately. I used Docker with the `centos:7` image and installed Miniconda into it and then Cutadapt with `conda install -c conda-forge -c bioconda cutadapt=3.3 python=3.6`. After that, running Cutadapt on a simple `test.fastq.gz` file did not give an error.

Please try to install Cutadapt into a separate Conda environment with something like `conda create -n cutadapt -c conda-forge -c bioconda cutadapt`. Then activate that environment and see if the error persists.

The error occurs at import time, so it shouldn’t have anything to do with the file itself nor the command-line options.

**Comment by rhpvorderman** [comment] 2021-03-30 10:12
Whoopsie. That is an error in python-isal.
I fixed it in the latest dev version.
The python zlib module has some constants `Z_RLE` and `Z_FIXED` that are also exposed by `isal_zlib` as an alias. But these are not always present in zlib. I ran into this issue myself when running python-isal on pypi.

A fix will be present in release 0.9.0. I will release that as quickly as possible.

**Comment by rhpvorderman** [comment] 2021-03-30 10:14
@marcelm, I will be watching cutadapt from now on as already two bugs related to python-isal were reported this week.
The CI is very extensive, but unfortunately it cannot catch all errors.

**Comment by marcelm** [comment] 2021-03-30 10:31
Thanks, then I don’t have to mention you in the future :-). And I’m just glad that I don’t have to dig into this, so no worries.

**Comment by rhpvorderman** [comment] 2021-03-31 06:06
@hero-outman 
This should have been fixed with the newest release of python-isal. Can you run `conda update python-isal` in the environment? It should update to version 0.9.0. Can you report if you still get the error?

**Comment by hero-outman** [comment] 2021-04-06 07:45
Hi dear fellows @marcelm  @rhpvorderman , I updated python-isal as rhpvorderman said, it works, No more error! So much thanks for your helping!

**Comment by marcelm** [comment] 2021-04-06 07:53
Perfect!

**Closed by marcelm** 2021-04-06 07:53 UTC
