### ISSUE TITLE
gzip output very slow

### ISSUE THREAD

**Issue by jsilter** [marcelm/cutadapt#119] opened 2015-04-13 20:53 UTC
Using cutadapt to gzip output directly is incredibly slow, as in it was taking hours before I killed it and just output non-gzipped files and then used the gzip command line utility (which took ~10 minutes). This was using Python 2.7.1. Cutadapt 1.5 didn't have this problem, but once I upgraded to Cutadapt 1.8 the slowdown was incredible.

**Comment by marcelm** [comment] 2015-04-13 20:58
Were you also reading in .gz files?

**Comment by jsilter** [comment] 2015-04-14 14:37
The reads were a small example set from Galaxys how-to (the adrenal set from https://usegalaxy.org/u/jeremy/p/galaxy-rna-seq-analysis-exercise)

cutadapt -m 20 -e 0.1 -q 20 --overlap 3 -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC -A AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATT -o 'Galaxy2-[adrenal_1.fastq].fastq.cutadapt.1.fq.gz' -p 'Galaxy3-[adrenal_2.fastq].fastq.cutadapt.2.fq.gz' 'Galaxy2-[adrenal_1.fastq].fastq' 'Galaxy3-[adrenal_2.fastq].fastq' > 'Galaxy2-[adrenal_1.fastq].fastq.cutadapt_report.txt'

I just tried running this on my Mac and it ran in ~10 seconds, but on the linux cluster I use (Redhat 6 I believe) it's very very slow. 5 minutes and counting so far. On the same cluster, cutadapt 1.5 (and single end trimming because paired end isn't available in that version) runs in a few seconds. So maybe it's a linux-specific thing.

**Comment by marcelm** [comment] 2015-04-14 16:06
Thanks for the detailed test case! However, I wasn’t able to reproduce the problem ... The trimming finishes in a few seconds on my machine as well.

I suspect that the program is indefinitely waiting for its gzip child process to finish (waiting for gzip to finish was one of the changes I did between 1.5 and 1.8).

Depending on how experienced you are, could you please do one or more of the following:

* Run `top` while cutadapt is running and see whether the CPU time of the cutadapt process is increasing or whether it justs "sits there" doing nothing.
* Change line 45 in cutadapt/xopen.py from `retcode = self.process.wait()` to `retcode = self.process.wait(10)`. (The 10 is a timeout.) To find out where that file is, run `python -c 'import cutadapt.xopen as x; print x.__file__'`. Then re-run the cutadapt command you gave and see if there is an error message.
* Perhaps run `strace -p 12345`, where 12345 is the process id of the python process that runs cutadapt, and paste the first few lines here.

**Comment by jsilter** [comment] 2015-04-14 16:41
I think you're right, I've attached a stacktrace from when I kill the process:

Traceback (most recent call last):
  File "~/test_cutadapt/bin/cutadapt", line 10, in <module>
    cutadapt.main()
  File "~/test_cutadapt/lib/python2.7/site-packages/cutadapt/scripts/cutadapt.py", line 848, in main
    f.close()
  File "~/test_cutadapt/lib/python2.7/site-packages/cutadapt/xopen.py", line 45, in close
    retcode = self.process.wait()
  File "/broad/software/free/Linux/redhat_6_x86_64/pkgs/python_2.7.1-sqlite3-rtrees/lib/python2.7/subprocess.py", line 1243, in wait
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/broad/software/free/Linux/redhat_6_x86_64/pkgs/python_2.7.1-sqlite3-rtrees/lib/python2.7/subprocess.py", line 471, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt

Interestingly when I ran my test script as a forked process it seemed to run fine (which means I couldn't use options 1 and 3 to debug); apparently subprocess.wait() doesn't take any arguments (which means I can't use option 2)

**Comment by marcelm** [comment] 2015-04-14 18:05
Ah, sorry for suggesting option 2. It seems the timeout parameter was added in Python 3.3.

Now I have to admit I’m not sure how to solve this. Since I cannot reproduce it locally, it’s hard to debug. In your case, you could perhaps fix it by just removing the `self.process.wait()` line. But I cannot do that in general because I added that as a fix for issue #89. I’ll have to think about this a bit.

**Comment by jsilter** [comment] 2015-04-14 18:47
Thanks, I appreciate it. It looks like there's a backport of subprocess for older python versions: https://pypi.python.org/pypi/subprocess32/. I'm not sure how easy that would be to include in cutadapt but it's a thought.

**Comment by marcelm** [comment] 2015-07-31 12:25
Issue #137 could be a duplicate of this one. The symptom was a hanging process when writing to more than one .gz-compressed output files, which seems to apply to your case. If so, then the problem should be fixed in cutadapt 1.8.3.
If you have the time, you could test whether it works with 1.8.3. Otherwise, I’ll just assume it’s fixed and close this issue.

**Closed** 2015-12-02 10:42 UTC
