### ISSUE TITLE
Malformed fastq sequence name not reported correctly

### ISSUE THREAD

**Issue by isaacovercast** [marcelm/cutadapt#312] opened 2018-06-20 16:43 UTC
Cutadapt 1.16. Python 2.7.15
Installed using conda through the bioconda channel.
`cutadapt --minimum-length 35 --max-n 5 --trim-n --output <outfile> <infile>

If you have a fastq file with a malformed sequence name line then cutadapt crashes and reports this, but the line number it reports is always `1`, so it's confusing and hard to debug. 

```
cutadapt: error: Line 1 in FASTQ file is expected to start with '@', but found 'NB501447:1'
```

Steps to reproduce:
- Create a file called wat.fq with this content:
```
@K00337:98:HLJJTBBXX:2:1107:18822:31576 1:N:0:2
CAATTCTAGTCCTGTTGAAAGTATGAAATTTTAGGGGAGTGGCGAAGAAGAAGTTGTCCGTTGTCTCGGTTGTTCGGACGGC
+
AEA/EAEEEAA<EAEE/E/EEEAEAEEEE<EE/E6EEEEEEEEE//E6EEE6EAEEAE<EEEEEAE<EEEEEEEAEE/EEE/
@NB501447:153:HHVTJBGX3:1:11108:1643:18342 1:N:0:1
CGCTACACGCAGGACGCTTTTTCACGTTCTGGTTGGTTGTGGACTGTTGATGCTAAAGGTGAGCCGCTTAAAGCTACCAGTT
+
/EEEEE<E<EEEA<EEAAEEEEEA/EE/EAE/EA<<EEAE/6///EEEEAAEEEEEAEEEE/EEEEEA/EE/EE//AEEEE<
@NB501447:153:HHVTJBGX3:1:11209:3881:10761 1:N:0:1
GACAGATGTATCCATCTGAATGCAATGAAGAAAACCACCATTACCAGCATTAACCGTCAAACTATCAAAATATAACGTTGAC
+
/EEA6EE6/EEEEEEEE/EEEAEAEE/AAA/EEEE/AA</AE/E/EEEEEEEEE<EAAEEEEEEEEEEEEEAEE/EAEEEEE
@NB501447:153:HHVTJBGX3:1:11210:24344:13292 1:N:0:1
CAATTCTGTCCGCCATGAGAAGCATTCCCAACAACTTCTCCAGGTCTGAAAACAACCAAGTGATTCAACCAAACGCTTTACC
+
/<E/EAEEEE<AAA/EAEEAA<EEEA/AEE/EEAE/EEE<EEEA/E6EEEEEEEEEEEE6E/EE//A6AAEE/E<EE/EEEE
@NB501447:153:HHVTJBGX3:1:11212:22116:9510 1:N:0:1
CAATTCTAGTCCTGTTGAAAGTATGAAATTTTAGGGGAGTGGCGAAGAAGAAGTTGTCCGTTGTCTCGGTTGTTCGGACGGC
+
/EEEEEEEEEEAEEEEEEEEEEEEEEEEEEEAEEEEEEEEEEEEE/EEEEEEEEEEEEEEEEEEEEEEEEEEEEAEEEEEEE
@NB501447:153:HHVTJBGX3:1:11301:25510:9733 1:N:0:1
CGCTACACGCAGGACGCTTTTTCACGTTCTGGTTGGTTGTGGCCTGTTGATGCTAAAGGTGAGCCGCTTAAAGCTACCAGTT
+
/AEEEEEE<EEA//EA//EEEEEA/EE/EEEEEAEEE/EEEEE//A<EEAEE/A/EA6EEEEAEEE6<E/AAAAEE6/EEEE
@NB501447:153:HHVTJBGX3:1:11311:25785:5510 1:N:0:1
CGCTACACGCAGGACGCTTTTTCACGTTCTGGTTGGTTGTGGCCTATTGATGCTAAAGGTGAGCCGATTAAAGCTACCAGTT
+
EEEEEE/EEAEA<EAAEE<EEEEEAEEA6AEEAEEEE</EA/AEEA<<A<AAEEEEEAEEEEEE/E/AEEEEEEEEEAEEEA
@NB501447:153:HHVTJBGX3:1:11311:19298:11642 1:N:0:1
CCAGATCGGAAGATCTCGGGTCGCCTTTTTTTTGAGAAAAAAAAAAAAATGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
+
EEEEAEE<EEEA/EEA//A////E/////A<//////AEEEEEEEA/E6/<<EEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
```
- run cutadapt --output wat.fq.gz wat.fq
- Watch it run fine
- Edit wat.fq and remove the '@' on line 9
- run cutadapt --output wat.fq.gz wat.fq
- Crashes
```
This is cutadapt 1.16 with Python 2.7.15
Command line parameters: --output wat.fq.gz wat.fq
Running on 1 core
Trimming 0 adapters with at most 10.0% errors in single-end mode ...
cutadapt: error: Line 1 in FASTQ file is expected to start with '@', but found 'NB501447:1'
```
Error is on line 9, not on line 1.

Thanks for the really cool software! Love it.

**Comment by marcelm** [comment] 2018-06-20 19:40
Thanks a lot for the report! I believe this is a regression in a recent version of cutadapt, possibly related to the addition of multi-core support. I’m currently working on the FASTQ parser actually. I’ll make sure to fix this problem while I’m at it.

**Comment by carlyraea** [comment] 2018-06-21 18:29
As a corollary, cutadapt is adding what looks like extra data to the output...here's some lines of normal data and then a line with extra data (causing the error above):

@NB501447:153:HHVTJBGX3:4:23611:8273:11823 1:N:0:1
CTTCCGATCTCTATGATCAATTCCCAGTATCCAATCGAGCTGTCTAGAAGTACTTACAAGAGAGTAGACCATGGCCAATATCA
+
EEAEEE<EEEEEEEEEEEEEEEEEEEEAEEEEEEEEE/EEEEEEEEEEEAEEEEEEEEEEEEEAAEE/E/EE/EEEEEEEEEE
@NB501447:153:HHVTJBGX3:4:23612:8393:7034 1:N:0:1
CAATTCCTAAAAGGTGTTGATGTTCCTCTATATATTGCTAAAGTGGAAGATAGAGAAGGAAAAAGCATTAACTATATTTGTAT
+
EEEEEEEEEEEEEAEEEEEEEEEEEEEEEEEEEEEEEEEAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAEEEEEEEEE
@NB501447:153:HHVTJBGX3:4:23612:13750:9971 1:N:0:1
CAATTCATCAACGATTTTGATAATTCCAAAATGGAGTCATTTAGGTCGAAGAAAAAGATTTATGCCTCCTTTCCTCAAAAGTT
+
EEEEEEEEEEEA<EEEEAEEEEEEAEEEEEEEAEEEEAAEAE/EEEEEEEEAEEEEEEEEEEEEEEEEEEEEEAEEEEEEEEE
**A//<6/AEEEEEEEE<EEEEEEEEEEEEEEEEEEE/**
@NB501447:153:HHVTJBGX3:2:23310:16113:12441 1:N:0:1
CCAGATCGGAAGATCCGTATTCCCGTTTTTTGTTTAAAAAAAAAAAAAAAAAGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
+
E/AAEEEEEE/EEAE/////</<//6/AE/EA/6///EEEEEEEEEEE//AA/6AEEEEEEEEEEEEEEEEEEEEEEEEEEEE
@NB501447:153:HHVTJBGX3:2:23310:1342:17932 1:N:0:1
CCAGATCGGAAGATCCGTATGCCCCTTTTTTGTTGAAAAAAAAAAAAAAAAAGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
+
E<EEEEEAEE/A/AE////////<6//<E/EA//////AEEEEEEEE6AAAA/6<AAEEEEEEEEEEEEEEEEEEEEEEEEEE
@NB501447:153:HHVTJBGX3:2:23310:8938:18021 1:N:0:1
CAATTCAAAGTTTTAGGGCAGAGCAAGCTTTGCAGCTTTGTGATTGTAAAAAACCTCAAAAAACTTGCGTAAAGAATGTGTCT
+
E/EAEEEEEEEEEAEEEEEEEEE/EEEEAAAEEEEEEEEEEEAEEEE6//66AAEEEEEEEEEEEEEEEEEEEEEEEEEEEEE

**Comment by marcelm** [comment] 2018-06-21 20:35
Sorry, I don’t follow. What did you do to get this file with the extra data?

**Comment by carlyraea** [comment] 2018-06-21 20:43
I ran cutadapt on my RADsequence data before submitting it to iPyrad.
iPyrad crashes because it doesn't recognize cutadapt's malformed files, and
when I searched through the specific files it flags, I realized there were
sometimes extra lines of data which cause the error. Here's the iPyrad
program log:

Cladonia_macilenta_edits/Cladia_aggregata.demux.trimmed_R1_.fastq.gz
/scratch/summit/caan8813/cladonia_demux/Cladia_aggregata.demux.fq

Running on 1 core

Trimming 1 adapter with at most 10.0% errors in single-end mode ...

cutadapt: error: Line 1 in FASTQ file is expected to start with '@', but
found 'EEEE/EEEEA'


As Isaac noted, they don't occur on Line 1, but it's also an odd problem
because it's adding an extra line of data. Thanks, I appreciate any help!

*Carly Anderson Stewart*
*PhD. Student, Tripp Lab*
*Ecology and Evolutionary Biology Department*
*University of Colorado at Boulder*

*Web: carlyandersonstewart.tumblr.com
<http://carlyandersonstewart.tumblr.com>*
*Blog: mycoblonde.tumblr.com <http://mycoblonde.tumblr.com>*

**Comment by marcelm** [comment] 2018-06-21 21:00
So is this what happened?

1. You ran cutadapt on some data X. Cutadapt produced output Y.
2. You took Y and fed it into iPyrad.
3. iPyrad runs cutadapt once more, but on Y. Cutadapt crashes because the file was damaged by the previous cutadapt round.

If this is what happened, please open a separate issue.

**Comment by carlyraea** [comment] 2018-06-21 21:21
Done, should be clearer. Thanks for any help!

*Carly Anderson Stewart*
*PhD. Student, Tripp Lab*
*Ecology and Evolutionary Biology Department*
*University of Colorado at Boulder*

*Web: carlyandersonstewart.tumblr.com
<http://carlyandersonstewart.tumblr.com>*
*Blog: mycoblonde.tumblr.com <http://mycoblonde.tumblr.com>*

**Comment by marcelm** [comment] 2018-10-03 13:12
This should be fixed now; thanks again for the report. In the next release of Cutadapt, it will print this error on your example above:
```
cutadapt: error: Error in FASTQ file at line 9: Line expected to start with '@', but found 'N'
```
There is still be a problem with incorrect line numbers when running on multiple cores, but that’s a separate issue.

**Closed by marcelm** 2018-10-03 13:12 UTC
