### ISSUE TITLE
Invalid line 10716930 in FASTQ file: Unexpected end of file\n')) after TWO runs of cutadapt

### ISSUE THREAD

**Issue by AliceLedent** [marcelm/cutadapt#343] opened 2018-11-02 15:25 UTC
Hi,
I'm using cutadapt 1.16 and python 2.7
I installed cutadapt with miniconda 4.5.11 on a cluster.
The error come from ipyrad 0.7.28

I runed cutadapt 2 times, the first time to remove the 3' adaptor and the second time to remove the 5' adaptor. Indeed, i don't want them to be linked. I'd like to remove either one or the other or both of them if present. The second time  i add the option -m 35 to only keep FASTQ sequences longer than 35bp cause i thus use ipyrad to analyses my RADseq data and this program is more efficient with longer sequences.

Previously i runned cutadapt only once (with the linked 3' and 5' adapter setting) and ipyrad was running without any problem, but now that i am running two times cutadapt, here is the two errors i got systematically when running ipyrad (in step 3 : clustering) : "Invalid line 10716930 in FASTQ file: Unexpected end of file\n'))" or "ERROR 	sample [96,1] failed in step [build_clusters]; error: ValueError(invalid literal for int() with base10: '1*\nCTGCAACTGCATCTGCCCCGGCACCATCGAGACGCCCTCGATGCTG')"

Do you think this could be related to cutadapt? I've already made a lot of tests to find a problem coming from ipyrad but it seems that the only option i have to explain this error is the fact that my input fastq.gz files for ipyrad are now the results of two cutadapt processes instead of one. The only other option that i added and could have changed the resulting fastq.gz files is the -m 35, but i don't see how this could be a problem?

Here are the two job files that i submitted for cutadapt on the cluster:
cutadapt -m 1 -a CWGAGATCGGAAGAGCGGTTCAGCAGGAATGCCGAG -A "CWGN{4}AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT" -A "CWGN{5}AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT" -A "CWGN{6}AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT" -A "CWGN{7}AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT" -A "CWGN{8}AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT" --nextseq-trim=20 -e 0.1 -o ./Cutadapt3/cutadapt_L001_R1_.fastq.gz -p ./Cutadapt3/cutadapt_L001_R2_.fastq.gz Undetermined_S0_L001_R1_001.fastq.gz Undetermined_S0_L001_R2_001.fastq.gz

srun cutadapt -m 35 --too-short-output ./Cutadapt35/too_short_L001_R1.txt --too-short-paired-output ./Cutadapt35/too_short_L001_R2.txt -g ^ACACTCTTTCCCTACACGACGCTCTTCCGATCT -G ^CTCGGCATTCCTGCTGAACCGCTCTTCCGATCT --nextseq-trim=20 -e 0.1 -o ./Cutadapt35/cutadapt_L001_R1_.fastq.gz -p ./Cutadapt35/cutadapt_L001_R2_.fastq.gz ./Cutadapt3/cutadapt_L001_R1_.fastq.gz ./Cutadapt3/cutadapt_L001_R2_.fastq.gz

Thanks again in advance!
Alice

**Comment by marcelm** [comment] 2018-11-02 19:43
Hi Alice,

I’m not an ipyrad user myself, but as far as I know, it uses Cutadapt internally to pre-process the reads. I don’t know why you had to run Cutadapt yourself, but possibly the error arises from the *third* Cutadapt run inside of ipyrad (unless you have disabled that – no idea if that is possible).

In any case, I think it is unlikely that there is a bug in Cutadapt that makes it produce these corrupt output files. I don’t want to exclude this possibility entirely, but in previous bug reports, it always turned out to be some other problem.

Here is what you could check:

- Run `cutadapt -o /dev/null file.fastq.gz` (with the correct file name of course) on the input files for ipyrad (that is, the output produced by Cutadapt). Cutadapt will read in the file and discard the output, but it will tell you whether there is a problem in the FASTQ file. If there isn’t, the problem is likely within ipyrad.

- Run `zcat file.fastq.gz | tail` on the problematic FASTQ files for which you get error messages to see the last couple of lines. If you know how a FASTQ file should look, you should be able to spot whether there is a problem.

- Check whether you have perhaps overdrafted your quota on the cluster. If the disk is almost full or a hard quota limit is almost reached, any written file would be truncated as soon the limit is reached. Note that even though the disk space currently may not be a problem, perhaps it was at the time you ran the jobs.

- Check the log output of the Cutadapt jobs that you ran on the cluster. If there was any problem writing the output files, there should be an error message.

> ERROR sample [96,1] failed in step [build_clusters]; error: ValueError(invalid literal for int() with base10: '1*\nCTGCAACTGCATCTGCCCCGGCACCATCGAGACGCCCTCGATGCTG')"

I suggest you report this to the ipyrad developers as it does not come from Cutadapt. Perhaps it’s a configuration problem?

I hope some of this helps!

**Comment by AliceLedent** [comment] 2018-11-05 09:00
Hi Marcel!

Thank you very much for your time. I have to use cutadapt before ipyrad cause i can't give different adapter sequences to ipyrad, it only checks for the common illumina adapters. And yes i asked ipyrad to not trim the sequences since i did it before with cutadapt.

I know this is unlikely that cutadapt is the problem, but since i'm stuck for more than a month now and we've tried to find the problem in ipyrad along with their developpers and nothing came out (we just noticed the problem is when vsearch is called), I'm now trying any other options i have in mind.

You made a point here with the quota on the cluster. Something weird is happening when i launch my jobs, it's like the cluster don't know the job is finished and killed it after the time quota is over. But when i look at the output files, everything seems correct and finished. But may be the program didn't write all the output and didn't warn me of this. So when i use those outputs as the inputs of the next step (3) it crashes!
Just to be sure, when you says "overdrafted your quota on the cluster" you mean the RAM memory i asked for for this specific job or the total amount of RAM of the cluster? Do you mean this could be because at the time i launched my jobs, two many users were on the front end or something like that? What is weird is that this happened every time i launched that specific job on that cluster.

I gonna run the two command lines you posted, but as you said, this is probably not the problem!
The cutadapt log files are clean.

I gonna try to launch my jobs on another cluster as well, may be this will be the solution!

Thank you very much!
Alice

**Comment by marcelm** [comment] 2018-11-05 10:34
> Thank you very much for your time. I have to use cutadapt before ipyrad cause i can't give different adapter sequences to ipyrad, it only checks for the common illumina adapters. And yes i asked ipyrad to not trim the sequences since i did it before with cutadapt.

Good. I think you need to find out at which step the corruption occurs. I can come up with the following:
- Cutadapt output is corrupt
- ipyrad step 1 output is corrupt (even though you tell ipyrad to skip it, if I understand correctly, perhaps the file is still copied somewhere. The corruption could happen there.)
- ipyrad step 2 output is corrupt.

> You made a point here with the quota on the cluster. Something weird is happening when i launch my jobs, it's like the cluster don't know the job is finished and killed it after the time quota is over. But when i look at the output files, everything seems correct and finished. But may be the program didn't write all the output and didn't warn me of this. So when i use those outputs as the inputs of the next step (3) it crashes!

This sounds highly suspicious! Even when the log files have been written correctly, your output file can still be incomplete.

I highly recommend that you check the generated FASTQ files after each step. Use the commands I gave. Or, because it is paired-end, try `zcat file.1.fastq.gz| wc -l` and `zcat file.2.fastq.gz|wc -l` to count the number of lines in each file. When they don’t match, you know something went wrong, and you don’t even have to start the next step.

> Just to be sure, when you says "overdrafted your quota on the cluster" you mean the RAM memory i asked for for this specific job or the total amount of RAM of the cluster? Do you mean this could be because at the time i launched my jobs, two many users were on the front end or something like that? What is weird is that this happened every time i launched that specific job on that cluster.

What I meant is the amount of hard disk space available to you. Our cluster implements project-specific disk space limits (disk quota). You may have that as well. Let’s say I get a quota of 1000 GB for a project. When I have used 999 GB and run a program that tries to write a file bigger than 1 GB, it will be able to write the first 1 GB, but then error out with an error message. If it was writing a FASTQ file, the FASTQ will be incomplete.

> I gonna run the two command lines you posted, but as you said, this is probably not the problem!
> The cutadapt log files are clean.

Try the commands also on any intermediate files.

> I gonna try to launch my jobs on another cluster as well, may be this will be the solution!

I think the actual problem is that your jobs do not finish properly. If they time out and get killed, anything can go wrong. Trying a different cluster could solve this.

**Comment by AliceLedent** [comment] 2018-11-05 10:44
Hi again,

Ok i'll do it right away, thank you very much!
I'll also check if i do have a disk quota per job!

Let you know!
Thanks!

**Comment by AliceLedent** [comment] 2018-11-05 14:37
Hi,

Thank you very much for your help! Indeed i know localize whoch step was really the problem. And it was not the step 3 where the software noticed the error but the step 2 which results in .fastq.gz files of different lengths! It seems like the software didn't complete totally the step eve if it thinks it did! I thus asked the people that develop ipyrad if they could help me now.

But i think you're totally right and this should be related to the cluster. I didn't find a disk quota per job but i there is a limit user. Limit that i overpassed a while ago. The people from the cluster let me use more than i'm suppose to for the duration of my ongoing project but i'm thinking may be now this amount of data is so huge that the cluster just dont support it. I gonna ask them as well.

So thanks for helping me!
Alice

**Comment by AliceLedent** [comment] 2018-11-06 11:07
Sure! Thanks!

**Comment by marcelm** [comment] 2019-02-27 12:53
Assuming this is not an issue in Cutadapt, I’m closing the issue now, but feel free to comment or re-open.

**Closed by marcelm** 2019-02-27 12:53 UTC

**Comment by AliceLedent** [comment] 2019-02-27 12:57
Hi,

Yes i'm so sorry, i forgot to close it, the issue was with the cluster i've been using! Since its maintenance, all problems have disapeared!

Thank you very much again!
Alice

----- Mail original -----
De: "Marcel Martin" <notifications@github.com>
À: "marcelm/cutadapt" <cutadapt@noreply.github.com>
Cc: "AliceLedent" <aledent@doct.ulg.ac.be>, "Author" <author@noreply.github.com>
Envoyé: Mercredi 27 Février 2019 13:53:19
Objet: Re: [marcelm/cutadapt] Invalid line 10716930 in FASTQ file: Unexpected end of file\n')) after TWO runs of cutadapt (#343)

Assuming this is not an issue in Cutadapt, I’m closing the issue now, but feel free to comment or re-open.

**Comment by marcelm** [comment] 2019-02-27 14:00
Great, thanks for letting me know!
