### ISSUE TITLE
Wrong information about primers in the output files

### ISSUE THREAD

**Issue by AnaSofia94** [marcelm/cutadapt#419] opened 2019-11-05 10:16 UTC
I'm using cutadapt 1.18 and python version 3.7.2.

I'm searching for primers information and output the results in a new file.

I have the different output files, because I'm using 3 commands to search for the primers of interest, like this:

primer1= cutadapt -b primer_Fw -b primer_rv -O 10 --trimmed-only > file_1.fastq

primer2= cutadapt -b primer_Fw -b primer_rv -O 10 --trimmed-only > file_2.fastq

primer3= cutadapt -b primer_Fw -b primer_rv -O 10 --trimmed-only > file_3.fastq

However, it appears that some primers are mixed within each file, for instance when I select a sequence from file_1 I get the information from the primer 3. I should get the information about the primer1 that file_1 contains. Is this normal?

Beside, the option: 'trimmed-only' is to remove the primers from the sequences, however I believe the primers aren't being removed, because when I calculate the length of the fragment, the size is bigger than what we were expecting. 

Thank you for the help.

**Comment by marcelm** [comment] 2019-11-05 10:31
Note you’re using an old Cutadapt version. If there’s a bug, it may have been fixed in a more recent version.

Can you give an example so I can understand better? It would be easiest for me if you can create a simple example (a FASTQ file with very few or just a single read), show which Cutadapt command you used to trim it and the output itself, and then explain in which way the result you got is different from what you expected.

> Beside, the option: 'trimmed-only' is to remove the primers from the sequences

`--trimmed-only` will remove reads that *do not* contain an adapter/primer.

**Comment by AnaSofia94** [comment] 2019-11-05 10:39
Im sorry I can't give you a proper example, because I can't share the information... 
Like I said, I have a sequence that has the information about the primer 1. However, when i blast that sequence I get the information about the second primer. And I would expect the sequence to only contain information about primer 1... 

Then whats the best option to remove the primers in each sequence? 

Thank you for the help.

**Comment by marcelm** [comment] 2019-11-05 11:23
Hi again,

you filed issue #383 a while ago where you showed a similar command line. I gave an answer, but haven’t heard back from you. Did you read my answer back then?

I pointed out that you should probably not use the `-b` option and that, if you provide two adapter sequences, Cutadapt will by default trim only one of them. Your issue probably caused by this: Cutadapt only removes one of the primers from each sequence. Which one that is depends on the exact sequence (most of the time, it would be the longer of the two). The other will still be left in and so you will find it if when BLASTing the trimmed sequence.

If you are trimming PCR primer pairs, then you should look into [linked adapters](https://cutadapt.readthedocs.io/en/latest/guide.html#linked-adapters). Using them would allow you to write something like this to trim both in one go:
```
cutadapt -a primer_fwd...primer_rev --trimmed-only input.fastq.gz > output.fastq.gz
```
And in your case, it appears that you actually want to split up your input file into three output files, depending on which primer pair you find. To do this, Cutadapt supports [demultiplexing](https://cutadapt.readthedocs.io/en/latest/guide.html#demultiplexing). Something like this might work (line breaks added for readability):
```
cutadapt
  -a one=primer1_fwd...primer1_rev
  -a two=primer2_fwd...primer2_rev
  -a three=primer3_fwd...primer3_rev
  -o "trimmed-{name}.fastq.gz"
  input.fastq.gz
```
Add more `-a` options as necessary. This will create output files `trimmed-one.fastq.gz`, `trimmed-two.fastq.gz`, `trimmed-three.fastq.gz` and `trimmed-unknown.fastq.gz`.

**Comment by AnaSofia94** [comment] 2019-11-05 12:11
but can i use option -a with more than a primer fw? For instance, I got a primer that has two forwards and share a reverse primer... Can I continue to use option a?

**Comment by marcelm** [comment] 2019-11-05 12:26
You would need to list all the combinations that are possible. If you can have primer1_fwd occur together with primer2_rev, then you would need to add `-a primer1_fwd...primer2_rev`.

However, if actually all (or many of these) combinations are possible, then it may be too much to list all the possibilites and you may not want to use linked adapters. Instead, you can list all the forward adapters with `-g primer1_fwd -g primer2_fwd` etc. and all the reverse ones with `-a primer1_rev -a primer2_rev` etc., and then add the option `--times=2` to tell Cutadapt that it should do two rounds of adapter trimming from each read. However, then you cannot use the builtin demultiplexing function anymore.

**Comment by AnaSofia94** [comment] 2019-11-05 12:28
So you're telling me that option -a has only to optios... I can't put it like this: -a primer1 -a primer2 -a primer rv.

**Comment by marcelm** [comment] 2019-11-05 12:55
You can use as many `-a` as you want.

**Comment by AnaSofia94** [comment] 2019-11-05 13:15
ok, thank you for the help. 
However I still have the same question. 
When I'm using file_1, I have the primer_1 and I only get the information to this primer. For instance, when I blast for fragments with primer 1, I should get the information regarding this primer. However, when I search for primer2 in file_2 I get the information about primer1 and primer2.

**Comment by marcelm** [comment] 2019-11-05 15:23
What is primer_1? As far as I understand, there’s both primer1_fwd and primer1_rev, right? Which one do you mean?

**Comment by marcelm** [comment] 2019-11-07 13:28
So let me describe the problem as I understand it. Can you please check whether what I wrote is correct?

First, you run Cutadapt like this:
```
cutadapt -b primer_Fw -b primer_rv -O 10 --trimmed-only input.fastq > file_1.fastq
```
where primer_Fw and primer_rv are the P53 primers. Then you randomly pick a sequence from the `file_1.fastq` file, and BLAST it against some database. You did not say which BLAST database you are using, but it appears to contain p53 and ATM (are you using the BLAST website?). The result you get is that BLAST shows a hit against ATM.

Some things you could check:
- Double-check you are using the correct primer sequences (even if you have done this already, do it again. Try to use a different way for checking them.)
- How many reads are in `file_1.fastq`, `file_2.fastq` and `file_3.fastq`? Compare that to how many reads there are in the input file.
- How often does the above problem happen? Is it for all the reads that you tested or only a couple? 
- Do you have the problem in the opposite direction, that is, do you find p53 when you expect ATM?

If you can get permission to share a small part of the data with me privately, I can offer to have a look (run `cutadapt --help|head` to see my e-mail address), but I understand of course if this is not possible.

**Comment by AnaSofia94** [comment] 2019-11-08 16:39
What you wrote is correct.
Some issues that you quote:
     -I have already checked the primer sequences, and they are correct.
     -This happens for some reads, not all of them
     -The same happens reversely.

I'm sorry, but I can't share a part of my data. Again, so sorry for the
trouble. Thank you for the help.

Marcel Martin <notifications@github.com> escreveu no dia quinta, 7/11/2019
à(s) 13:28:

**Comment by marcelm** [comment] 2019-11-08 17:01
Ok. My guess at the moment is that your primer sequences are similar to each other. I guess this is what you meant here:
> I got a primer that has two forwards and share a reverse primer...

Let’s call the six primers primer1_fwd, primer1_rev, primer2_fwd, primer2_rev, primer3_fwd and primer3_rev. Is it correct that some of these are identical?

**Comment by marcelm** [comment] 2019-11-20 10:13
Hi, in case you fixed your problem, please let me know whether you have any suggestions for how to improve Cutadapt so that others don’t get the same problems. I’ll close this issue soon otherwise.

**Comment by AnaSofia94** [comment] 2019-11-20 10:23
I haven't solved the problem, the only way to ensure my result was to
delimit the length of the fragment. Thanks

Marcel Martin <notifications@github.com> escreveu no dia quarta, 20/11/2019
à(s) 10:13:

**Closed** 2020-04-22 10:25 UTC
