### ISSUE TITLE
cutadapt paired-end with gz output created truncated *.gz files

### ISSUE THREAD

**Issue by songli** [marcelm/cutadapt#136] opened 2015-07-10 21:04 UTC
here is my command line:

```
cutadapt -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC -A AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATT --minimum-length 50 -o t1.fastq.gz -p t2.fastq.gz Sample_R1.part.trim.fastq.gz Sample_R2.part.trim.fastq.gz > cutadapt.log
```

This command will finish but the resulted gz file is missing few characters at the end resulted in truncated gz files.  No problem when using non-gz files as output.

**Comment by marcelm** [comment] 2015-07-11 08:53
Do you have any other information that could help me reproduce the problem?

**Comment by marcelm** [comment] 2015-07-31 12:14
Feel free to add comments, but since there is too little information for me to reproduce the problem, I will close the issue for now.

**Closed by marcelm** 2015-07-31 12:14 UTC
