### ISSUE TITLE
Cutadapt BadGzipFile errors 

### ISSUE THREAD

**Issue by sg3451** [marcelm/cutadapt#496] opened 2020-11-26 09:43 UTC
<!--

- Cutadapt version 3.0, Python version 2.7.11
- installed Cutadapt from conda
- Command line parameters: -j 1 -e 0.1 -q 20 -O 1 -a AGATCGGAAGAGC ../../brosky/data/IMAGINE-4241_S1-R1.fastq.gz

I have several fastq.gz files that I am passing through cutadapt (using the Trimgalore wrapper). The files are part of the same experiment and were generated on the same Illumina machine. For some files, I have no problem in generating trimmed fastq files. But for some files, cutadapt is throwing the following error during the quality and adapter trimming step. In this step, sometimes upto 30000000 sequences are processed before the error appears; in other cases, the traceback error appears right after the command line parameters, prior to any sequence processing. Details are given below:
--------------------------------------------------------------------------------------------------------------------
(cutadaptenv) [gmssujo@login-7-0 TrimGalore-0.6.6]$ ./trim_galore ../../brosky/data/IMAGINE-4241_S1-R1.fastq.gz
Multicore support not enabled. Proceeding with single-core trimming.
Path to Cutadapt set as: 'cutadapt' (default)
Cutadapt seems to be working fine (tested command 'cutadapt --version')
Cutadapt version: 3.0
single-core operation.
No quality encoding type selected. Assuming that the data provided uses Sanger encoded Phred scores (default)

AUTO-DETECTING ADAPTER TYPE
===========================
Attempting to auto-detect adapter type from the first 1 million sequences of the first file (>> ../../brosky/data/IMAGINE-4241_S1-R1.fastq.gz <<)

Found perfect matches for the following adapter sequences:
Adapter type    Count   Sequence        Sequences analysed      Percentage
Illumina        5       AGATCGGAAGAGC   1000000 0.00
smallRNA        0       TGGAATTCTCGG    1000000 0.00
Nextera 0       CTGTCTCTTATA    1000000 0.00
Using Illumina adapter for trimming (count: 5). Second best hit was smallRNA (count: 0)

Writing report to 'IMAGINE-4241_S1-R1.fastq.gz_trimming_report.txt'

SUMMARISING RUN PARAMETERS
==========================
Input filename: ../../brosky/data/IMAGINE-4241_S1-R1.fastq.gz
Trimming mode: single-end
Trim Galore version: 0.6.6
Cutadapt version: 3.0
Number of cores used for trimming: 1
Quality Phred score cutoff: 20
Quality encoding type selected: ASCII+33
Adapter sequence: 'AGATCGGAAGAGC' (Illumina TruSeq, Sanger iPCR; auto-detected)
Maximum trimming error rate: 0.1 (default)
Minimum required adapter overlap (stringency): 1 bp
Minimum required sequence length before a sequence gets removed: 20 bp
Output file(s) will be GZIP compressed

Cutadapt seems to be fairly up-to-date (version 3.0). Setting -j 1
Writing final adapter and quality trimmed output to IMAGINE-4241_S1-R1_trimmed.fq.gz

  >>> Now performing quality (cutoff '-q 20') and adapter trimming in a single pass for the adapter sequence: 'AGATCGGAAGAGC' from file ../../brosky/data/IMAGINE-4241_S1-R1.fastq.gz <<<
This is cutadapt 3.0 with Python 3.8.6
Command line parameters: -j 1 -e 0.1 -q 20 -O 1 -a AGATCGGAAGAGC ../../brosky/data/IMAGINE-4241_S1-R1.fastq.gz
Processing reads on 1 core in single-end mode ...
Traceback (most recent call last):
  File "/home/gmssujo/software/miniconda3/envs/cutadaptenv/bin/cutadapt", line 10, in <module>
    sys.exit(main_cli())
  File "/home/gmssujo/software/miniconda3/envs/cutadaptenv/lib/python3.8/site-packages/cutadapt/__main__.py", line 825, in main_cli
    main(sys.argv[1:])
  File "/home/gmssujo/software/miniconda3/envs/cutadaptenv/lib/python3.8/site-packages/cutadapt/__main__.py", line 892, in main
    stats = r.run()
  File "/home/gmssujo/software/miniconda3/envs/cutadaptenv/lib/python3.8/site-packages/cutadapt/pipeline.py", line 870, in run
    (n, total1_bp, total2_bp) = self._pipeline.process_reads(progress=self._progress)
  File "/home/gmssujo/software/miniconda3/envs/cutadaptenv/lib/python3.8/site-packages/cutadapt/pipeline.py", line 324, in process_reads
    for read in self._reader:
  File "src/dnaio/_core.pyx", line 173, in fastq_iter
  File "/home/gmssujo/software/miniconda3/envs/cutadaptenv/lib/python3.8/gzip.py", line 292, in read
    return self._buffer.read(size)
  File "/home/gmssujo/software/miniconda3/envs/cutadaptenv/lib/python3.8/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/home/gmssujo/software/miniconda3/envs/cutadaptenv/lib/python3.8/gzip.py", line 470, in read
    self._read_eof()
  File "/home/gmssujo/software/miniconda3/envs/cutadaptenv/lib/python3.8/gzip.py", line 516, in _read_eof
    raise BadGzipFile("CRC check failed %s != %s" % (hex(crc32),
gzip.BadGzipFile: CRC check failed 0xf1fd040 != 0xa53b44c4

Cutadapt terminated with exit signal: '256'.
Terminating Trim Galore run, please check error message(s) to get an idea what went wrong...

**Comment by marcelm** [comment] 2020-11-26 10:52
I’ll be happy to help, but please more details so that I may know what the problem is about. Or did you open this issue by mistake?

**Comment by sg3451** [comment] 2020-11-26 11:48
Dear Marcel,

This was my first foray into GitHub and I am pretty sure I messed it up. I
didn't open the issue by mistake but am also not sure if you could find
anything to read! Below is the text that I tried to put in there. Briefly,
I am using Trimgalore wrapper to apply cutadapt to some fastq files from a
methylseq study. It is generating trimmed fastqs for some of the files
successfully but not for all of them. The error message is included below
(and being primarily a biologist, I have no idea what is wrong).
----------------------------------------------------------------------
(cutadaptenv) [gmssujo@login-7-0 TrimGalore-0.6.6]$ cutadapt --version
3.0

(cutadaptenv) [gmssujo@login-7-0 TrimGalore-0.6.6]$ ./trim_galore
../../brosky/data/IMAGINE-6644_S4-R1.fastq.gz
Multicore support not enabled. Proceeding with single-core trimming.
Path to Cutadapt set as: 'cutadapt' (default)
Cutadapt seems to be working fine (tested command 'cutadapt --version')
Cutadapt version: 3.0
single-core operation.
No quality encoding type selected. Assuming that the data provided uses
Sanger encoded Phred scores (default)

AUTO-DETECTING ADAPTER TYPE
===========================
Attempting to auto-detect adapter type from the first 1 million sequences
of the first file (>> ../../brosky/data/IMAGINE-6644_S4-R1.fastq.gz <<)

Found perfect matches for the following adapter sequences:
Adapter type    Count   Sequence        Sequences analysed      Percentage
Illumina        7       AGATCGGAAGAGC   1000000 0.00
smallRNA        0       TGGAATTCTCGG    1000000 0.00
Nextera 0       CTGTCTCTTATA    1000000 0.00
Using Illumina adapter for trimming (count: 7). Second best hit was
smallRNA (count: 0)

Writing report to 'IMAGINE-6644_S4-R1.fastq.gz_trimming_report.txt'

SUMMARISING RUN PARAMETERS
==========================
Input filename: ../../brosky/data/IMAGINE-6644_S4-R1.fastq.gz
Trimming mode: single-end
Trim Galore version: 0.6.6
Cutadapt version: 3.0
Number of cores used for trimming: 1
Quality Phred score cutoff: 20
Quality encoding type selected: ASCII+33
Adapter sequence: 'AGATCGGAAGAGC' (Illumina TruSeq, Sanger iPCR;
auto-detected)
Maximum trimming error rate: 0.1 (default)
Minimum required adapter overlap (stringency): 1 bp
Minimum required sequence length before a sequence gets removed: 20 bp
Output file(s) will be GZIP compressed

Cutadapt seems to be fairly up-to-date (version 3.0). Setting -j 1
Writing final adapter and quality trimmed output to
IMAGINE-6644_S4-R1_trimmed.fq.gz


  >>> Now performing quality (cutoff '-q 20') and adapter trimming in a
single pass for the adapter sequence: 'AGATCGGAAGAGC' from file
../../brosky/data/IMAGINE-6644_S4-R1.fastq.gz <<<
10000000 sequences processed
20000000 sequences processed
30000000 sequences processed
This is cutadapt 3.0 with Python 3.8.6
Command line parameters: -j 1 -e 0.1 -q 20 -O 1 -a AGATCGGAAGAGC
../../brosky/data/IMAGINE-6644_S4-R1.fastq.gz
Processing reads on 1 core in single-end mode ...
Traceback (most recent call last):
  File "/home/gmssujo/software/miniconda3/envs/cutadaptenv/bin/cutadapt",
line 10, in <module>
    sys.exit(main_cli())
  File
"/home/gmssujo/software/miniconda3/envs/cutadaptenv/lib/python3.8/site-packages/cutadapt/__main__.py",
line 825, in main_cli
    main(sys.argv[1:])
  File
"/home/gmssujo/software/miniconda3/envs/cutadaptenv/lib/python3.8/site-packages/cutadapt/__main__.py",
line 892, in main
    stats = r.run()
  File
"/home/gmssujo/software/miniconda3/envs/cutadaptenv/lib/python3.8/site-packages/cutadapt/pipeline.py",
line 870, in run
    (n, total1_bp, total2_bp) =
self._pipeline.process_reads(progress=self._progress)
  File
"/home/gmssujo/software/miniconda3/envs/cutadaptenv/lib/python3.8/site-packages/cutadapt/pipeline.py",
line 324, in process_reads
    for read in self._reader:
  File "src/dnaio/_core.pyx", line 173, in fastq_iter
  File
"/home/gmssujo/software/miniconda3/envs/cutadaptenv/lib/python3.8/gzip.py",
line 292, in read
    return self._buffer.read(size)
  File
"/home/gmssujo/software/miniconda3/envs/cutadaptenv/lib/python3.8/_compression.py",
line 68, in readinto
    data = self.read(len(byte_view))
  File
"/home/gmssujo/software/miniconda3/envs/cutadaptenv/lib/python3.8/gzip.py",
line 470, in read
    self._read_eof()
  File
"/home/gmssujo/software/miniconda3/envs/cutadaptenv/lib/python3.8/gzip.py",
line 516, in _read_eof
    raise BadGzipFile("CRC check failed %s != %s" % (hex(crc32),
gzip.BadGzipFile: CRC check failed 0xf9f9ff5f != 0x8bc23bc9


Cutadapt terminated with exit signal: '256'.
Terminating Trim Galore run, please check error message(s) to get an idea
what went wrong...

*A book must be the axe for the frozen sea inside us - Franz Kafka*

**Comment by marcelm** [comment] 2020-11-26 12:30
That looks better :-).

I’m not involved with TrimGalore development, so the first step would be to try to reproduce the problem with Cutadapt only. If the error disappears, it is probably a TrimGalore problem and should be reported to its developers.

From the log, it appears that you should try this command:
```
cutadapt -j 1 -e 0.1 -q 20 -O 1 -o /dev/null -a AGATCGGAAGAGC ../../brosky/data/IMAGINE-6644_S4-R1.fastq.gz
```
I added the `-o /dev/null` because otherwise the FASTQ file contents would be printed in your terminal.

Assuming that this command gives you the same error message, please run the following command to see whether the `.gz` file can be decompressed succesfully:
```
zcat ../../brosky/data/IMAGINE-6644_S4-R1.fastq.gz > /dev/null
```
If you get an error message, then the file is likely corrupt. If so, do you have a backup/copy of it somewhere? Try to see whether the two versions are the same by running
```
md5sum filename1 filename2
```
(replacing `filename1` and `filename2` with the actual file names). This will show you the MD5 checksums for both files. If the checksums are different, it means that the files are different (and probably something went wrong when copying the file).

**Comment by sg3451** [comment] 2020-11-27 08:04
Dear Marcel,

It is exactly what you had suspected. Files that didn't match their MD5s
were generating the error in cutadapt. Files with matched MD5s worked
perfectly.

Thank you again for responding so quickly!

Regards,

Sujoy

*A book must be the axe for the frozen sea inside us - Franz Kafka*

**Comment by marcelm** [comment] 2020-11-27 09:04
Ah, sometimes I make good guesses :-)  -- glad I could help!

I’ll close this issue then. Please open a new one if you have another problem!

**Closed by marcelm** 2020-11-27 09:04 UTC
