### ISSUE TITLE
3' Anchored trim is not working

### ISSUE THREAD

**Issue by LindsayJY** [marcelm/cutadapt#124] opened 2015-05-20 16:39 UTC
I am attempting to trim the primer sequencing off of the 5' AND 3' ends of PE reads. Below is an example of the PE reads, with primers in CAPITALS.

Forward PE Read: 5’CTCTTTACCTTGACCCACAAATAttctaagagatttgtctgcaagagagtttcaacaaatgtttgtcctttgaccactgttctgtattgaaccctagggtgagcctggtccagctggctccaaaggagagagcggtaacaagggtgagcccgtaagtagctctatcatcacacttttataaagttaattgtttttctCATTCCAGTTTCTCCAGCTG-3’
Reverse PE Read:
5’CAGCTGGAGAAACTGGAATGagaaaaacaattaactttataaaagtgtgatgatagagctacttacgggctcacccttgttaccgctctctcctttggagccagctggaccaggctcaccctagggttcaatacagaacagtggtcaaaggacaaacatttgttgaaactctcttgcagacaaatctcttagaaTATTTGTGGGTCAAGGTAAAGAG-5’

I have been able to use the following command line to trim the 5' primers (using the anchored setting) with much success:

cutadapt -g ^CTCTTTACCTTGACCCACAAAT -G ^CAGCTGGAGAAACTGGAATG -o output.R1.fastq -p output.R2.fastq input.R1.fastq input.R2.fastq --no-indels

However, I cannot get ANYTHING working for the 3' trimming. Below is the command line that I believe should be used, except nothing gets trimmed! (Also, I get an error when I try to use --no-indels, saying it's only supported for anchored trimming, but I AM doing anchored trimming!)

cutadapt -a CATTCCAGTTTCTCCAGCTG$ -A TATTTGTGGGTCAAGGTAAAGAG$ -o output.R1.fastq -p output.R2.fastq input.R1.fastq input.R2.fastq

I have also tried not doing paired end mode (see below for an example), and that also trims absolutely nothing:

cutadapt -a CATTCCAGTTTCTCCAGCTG$ -o output.R1.fastq input.R1.fastq

If I try 3' trimming without anchoring, other amplicons that overlap this region end up cut in half or entirely deleted depending on where the sequence appears in the read, therefore I REALLY need anchoring for this to work. I've even tried not doing the reverse complements for the 3' trimming, thinking maybe CutAdapt performs the rc and that's why the sequence is being trimmed. Nope, no luck there either.

Any ideas? I've been going nuts.

**Comment by marcelm** [comment] 2015-05-20 18:21
Are you really using cutadapt? You write `skewer` in your examples, which is a different program.

**Comment by LindsayJY** [comment] 2015-05-20 18:24
Yes! Sorry. I just started to use skewer today to see if that program will work, so I mistakenly typed skewer. I will see if I can edit my post to reflect that.

**Comment by marcelm** [comment] 2015-05-21 15:09
Thanks for fixing the post. Thanks for reporting that `--no-indels` does not work with `-A ADAPTER$`. I’ve just fixed that and the fix will be in the next version of cutadapt.

However, I’ve tried your examples (without `--no-indels`) and they work here - the adapters are removed correctly. Which version of cutadapt are you using?

In the paired-end examples you give, you use the same file names twice. I guess you are not actually doing this, but if you were you would be overwriting intermediate files that are needed. In reality, you should create an intermediate pair of files and use that as input for the second run of cutadapt.

I would like to concentrate on getting the simple example (just trimming one read, no paired-end) working first. Since the example you posted works here, perhaps you could send me a (shortened) FASTQ file that shows the problem (via e-mail is ok).

**Comment by LindsayJY** [comment] 2015-05-21 16:00
For the sake of the example, I used the same file names, but they have
always been different when we try the commands. Furthermore, we have not
even attempted sequential trimming yet, because 1) the 3' just hasn't
worked for us by itself yet, and 2) the goal is to run PE 5' and 3'
trimming in the same command line, as in:

cutadapt -g ^CTCTTTACCTTGACCCACAAAT -G ^CAGCTGGAGAAACTGGAATG -a
CATTCCAGTTTCTCCAGCTG$ -A TATTTGTGGGTCAAGGTAAAGAG$ -o output.R1.fastq -p
output.R2.fastq input.R1.fastq input.R2.fastq *--no-indels -n 2*

Using -n = 2 would ensure the 5' and 3' primers are trimmed from each read,
correct?

We are using version 1.8. I asked my coworker, who installed the software,
and she said she was only able to find 1.8 despite seeing "1.9.dev1" in the
documentation. Is the version we're using causing the problem?

How do I send you a direct email? Do you want the original FASTQ file (no
trimming) or the FASTQ that results from the failed 3' trimming (which is
essentially the same as the former...)?

Thanks for all your help with this.

On Thu, May 21, 2015 at 10:09 AM, Marcel Martin <notifications@github.com>
wrote:

> Thanks for fixing the post. Thanks for reporting that --no-indels does
> not work with -A ADAPTER$. I’ve just fixed that and the fix will be in
> the next version of cutadapt.
>
> However, I’ve tried your examples (without --no-indels) and they work
> here - the adapters are removed correctly. Which version of cutadapt are
> you using?
>
> In the paired-end examples you give, you use the same file names twice. I
> guess you are not actually doing this, but if you were you would be
> overwriting intermediate files that are needed. In reality, you should
> create an intermediate pair of files and use that as input for the second
> run of cutadapt.
>
> I would like to concentrate on getting the simple example (just trimming
> one read, no paired-end) working first. Since the example you posted works
> here, perhaps you could send me a (shortened) FASTQ file that shows the
> problem (via e-mail is ok).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/marcelm/cutadapt/issues/124#issuecomment-104313662>.
>



-- 
Lindsay Yanakakis, MS
lindsay.yanakakis@gmail.com
360-471-8885

**Comment by LindsayJY** [comment] 2015-05-21 16:26
My coworker tells me that "pip" still has v1.8 as the cutadapt version.

**Comment by LindsayJY** [comment] 2015-05-21 17:30
I have solved the problem. Your software is functioning perfectly. It turns out I was mistaken about the layout of my reads; there is actually a Tag sequence following the 3' primer as well as the barcode, so anchored trimming cannot be used. I can successfully trim the 3' primers if I include the reverse complement of the Primer-TAG sequence without worrying about trimming overlapping amplicons by setting the overlap option (-O) to 35, which is 2 bp below the shortest Primer-Tag sequence. 

I apologize for using up your time. Thanks a bunch for developing this awesome software!

**Comment by marcelm** [comment] 2015-05-21 17:30
1.9.dev1 is an unreleased development version. Version 1.8 is the most recent stable version, and it should work with the example you gave. Using `-n 2` is indeed the preferred way of trimming in a single pass. My e-mail address is printed when you run `cutadapt --help` (at the very top). Send me the original FASTQ file and the exact command line that you are using. ...

**Comment by marcelm** [comment] 2015-05-21 17:30
Oh, hi, then I can stop writing a reply ...

**Comment by marcelm** [comment] 2015-05-21 17:32
Great to hear you solved it and don’t worry about my time spend - that’s how it works sometimes. And hearing that there is actually not a bug is also nice :-)

I’m closing this as resolved since you did find the bug about the `--no-indels` parameter not working.

**Closed by marcelm** 2015-05-21 17:32 UTC

**Comment by LindsayJY** [comment] 2015-05-21 17:40
One suggestion though: I currently have to run two commands separately because the -O option being set to 35 does not work for my 5' primers, as their sequences are only about 25 bp. It would be great if we could specify minimum overlaps for 5' and 3' trimming separately. Not really sure how this would be executed.

**Comment by marcelm** [comment] 2015-05-21 17:50
I’m not 100% sure I understand the layout of your reads, but if the sequence following the primer has a fixed length, you could use `N` bases in the adapter sequence. So if your reads always end with `ACGT` plus three variable bases, you could use `-a ACGTNNN$` to trim that. I’ll also think about the suggestion regarding the minimum overlap.

**Comment by LindsayJY** [comment] 2015-05-21 17:53
Hm... Using the PRIMERNNN$ method may allow me to do all of this in one
command line without the overlap being an issue... Thanks for the tip!

On Thu, May 21, 2015 at 12:50 PM, Marcel Martin <notifications@github.com>
wrote:

> I’m not 100% sure I understand the layout of your reads, but if the
> sequence following the primer has a fixed length, you could use N bases
> in the adapter sequence. So if your reads always end with ACGT plus three
> variable bases, you could use -a ACGTNNN$ to trim that. I’ll also think
> about the suggestion regarding the minimum overlap.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/marcelm/cutadapt/issues/124#issuecomment-104370316>.
>



-- 
Lindsay Yanakakis, MS
lindsay.yanakakis@gmail.com
360-471-8885

**Comment by LindsayJY** [comment] 2015-05-21 18:10
It seems that while all of our barcodes are 10 bp in length, there may be 1-4 additional bases after the barcode. In this case, I'm assuming the PRIMERNNN$ solution would not work, because the number of Ns varies? Or would 1 or two extra bases be okay because it's within the limits of the error tolerance? I'm hoping 1-2 more Ns WILL be tolerated because I just realized not all of my reads will sequence through to the Tag sequence (my amplicons are of variable length), so if the -O option is set to 35, MANY reads will not get trimmed that were still able to read through to the primer.

**Comment by LindsayJY** [comment] 2015-05-21 18:13
Another option would be allowing the user to specify something like: Only trim when the sequence appears within X bases from the end of the read (or the beginning of the read for 5' adapters/primers).

**Comment by marcelm** [comment] 2015-05-22 07:43
I agree it would be helpful to have a little more control over where the adapter is allowed to be, but using non-anchored 3' adapters is fine most of the time, most likely also in your case. I’d also set the overlap a bit lower. The probabilty of the adapter sequence occurring by chance somewhere you are not expecting it is vanishingly small, so if cutadapt finds something (even if it’s not at the end of the read), it probably is something, maybe a technical artifact (like primer dimers).

| Or would 1 or two extra bases be okay because it's within the limits of the error tolerance?

Yes, these would count as insertions and if there are not too many, they are allowed (maximum error rate is 10% by default).
