### ISSUE TITLE
All reads written to untrimmed rather than trimmed output files, although trimming was successful with -G

### ISSUE THREAD

**Issue by griffinp** [marcelm/cutadapt#243] opened 2017-05-04 01:49 UTC
Hi,

I have what I think is an instance of the same issue as described in #242 (I wanted to raise it as a new issue though since the title of that issue doesn't reflect what I'm trying to do with my data).

I am running three separate cutadapt steps. In Step1, I run quality trimming with a dummy adapter sequence. This works fine and output files all look good.

In Step2, I want to trim an anchored adapter from the 5' end of Read 1, writing trimmed and untrimmed output files for both Read 1 and Read 2 as follows:

Command line parameters: -g ^GGTCAACAAATCATAAAGATATTGG -e 0.1 --untrimmed-output ChironCONT-NEB_S41_L001_LCO1490_MLepR2_step2_untrimmed_R1.fastq --untrimmed-paired-output ChironCONT-NEB_S41_L001_LCO1490_MLepR2_step2_untrimmed_R2.fastq -o ChironCONT-NEB_S41_L001_LCO1490_MLepR2_step2_trimmed_R1.fastq --paired-output ChironCONT-NEB_S41_L001_LCO1490_MLepR2_step2_trimmed_R2.fastq ChironCONT-NEB_S41_L001_qtrimmed_R1.fastq ChironCONT-NEB_S41_L001_qtrimmed_R2.fastq
Trimming 1 adapter with at most 10.0% errors in paired-end legacy mode ...
Finished in 4.61 s (20 us/read; 3.04 M reads/minute).

=== Summary ===

Total read pairs processed:            233,553
  Read 1 with adapter:                  37,474 (16.0%)
  Read 2 with adapter:                       0 (0.0%)
Pairs written (passing filters):       233,553 (100.0%)

Total basepairs processed:   112,514,201 bp
  Read 1:    56,089,391 bp
  Read 2:    56,424,810 bp
Total written (filtered):    111,577,867 bp (99.2%)
  Read 1:    55,153,057 bp
  Read 2:    56,424,810 bp

This appears to work fine: both trimmed and untrimmed output files are produced.

In Step3, I trim an anchored adapter trimming from the 5' end of Read 2 as follows:

This is cutadapt 1.13 with Python 2.7.12
Command line parameters: -G ^CTTATATTATTTATTCGTGGGAAAGC -e 0.1 --untrimmed-output ChironCONT-NEB_S41_L001_LCO1490_MLepR2_step3_untrimmed_R1.fastq --untrimmed-paired-output ChironCONT-NEB_S41_L001_LCO1490_MLepR2_step3_untrimmed_R2.fastq -o ChironCONT-NEB_S41_L001_LCO1490_MLepR2_step3_trimmed_R1.fastq --paired-output ChironCONT-NEB_S41_L001_LCO1490_MLepR2_step3_trimmed_R2.fastq ChironCONT-NEB_S41_L001_LCO1490_MLepR2_step2_trimmed_R1.fastq ChironCONT-NEB_S41_L001_LCO1490_MLepR2_step2_trimmed_R2.fastq
Trimming 1 adapter with at most 10.0% errors in paired-end mode ...
Finished in 0.88 s (23 us/read; 2.56 M reads/minute).

=== Summary ===

Total read pairs processed:             37,474
  Read 1 with adapter:                       0 (0.0%)
  Read 2 with adapter:                  31,977 (85.3%)
Pairs written (passing filters):        37,474 (100.0%)

Total basepairs processed:    20,075,566 bp
  Read 1:     9,531,317 bp
  Read 2:    10,544,249 bp
Total written (filtered):     19,245,353 bp (95.9%)
  Read 1:     9,531,317 bp
  Read 2:     9,714,036 bp 
  
So according to the output summary, this trimming worked and 85.3% of Read2s were trimmed. **But, all the output reads are written to the untrimmed output files rather than the trimmed output files: the trimmed output files are created, but empty.** 

Please let me know if I can provide any more info that'd be of use in diagnosing this problem!

**Comment by marcelm** [comment] 2017-05-04 11:06
Your issue is indeed the same as #242, which is possibly a bug in cutadapt. It occurs when you try to trim only the R2 reads, which you do in your step 3. Please also follow the discussion on #242 (I am traveling and will reply there later).

Of course the problem should be fixed, but note that cutadapt’s paired-end mode was not meant to be used in this way. Instead of running quality trimming and trimming of R1 and R2 in three different steps, you can do all of this at once with a single invocation of cutadapt (just use all the `-q`, `-g` and `-G` options at once). You get fewer intermediate files and it will be faster. Note that the `--untrimmed-output` files will then contain all the reads where R1 *or* R2 were untrimmed.

If you for some reason do not want this, perhaps because you want to have the untrimmed output split into "primer not found in R1" and "primer not found in R2", I suggest this workaround until the problem is repaired: In step 2, swap the R1 and R2 files (both input and output) and use the lowercase `-g` option. This is the procedure described in the documentation in the second half of the section [Legacy paired-end read trimming](http://cutadapt.readthedocs.io/en/stable/guide.html#legacy-paired-end-read-trimming).

A few other tips:

* In cutadapt 1.13, the dummy adapter is no longer needed when you want to do only quality trimming.
* There are (in my opinion), very few reasons why FASTQ files should ever be stored uncompressed. Cutadapt can read and write compressed FASTQ files. And you can use tools such as `zless` to work with `.gz` files.

**Comment by griffinp** [comment] 2017-05-04 23:58
Thanks very much for your detailed response @marcelm. For now, your suggestion of swapping the R1 and R2 files will solve my problem - thanks.

I wish I could run cutadapt in a single step for this project... however I have to do it this way because the complicated library design (multiple amplicons, some with the same forward primer but a different reverse primer) means I need to be able to split up the untrimmed output as you suggest. 

About the quality-trimming-only step: I did first try this without a dummy adapter, but I had the impression (maybe this was incorrect?) that it was only trimming R1 and not R2 in that case. Will have another look. 

Thanks again for your help and for the workaround!

**Comment by marcelm** [comment] 2017-05-05 18:36
Ok, great it helps! Yes, I think you are right that only R1 is trimmed. It’s a bit annoying, but necessary for backwards compatibility. I will close this now in favor of #242.

**Closed by marcelm** 2017-05-05 18:36 UTC
