### ISSUE TITLE
pip install cutadapt failing due to missing cython

### ISSUE THREAD

**Issue by necrolyte2** [marcelm/cutadapt#138] opened 2015-07-23 14:44 UTC
Not sure if this is a pip issue, setuptools or something with cutadapt's install process but here is what is happening

#### System Inf0

```
$> cat /etc/redhat-release 
Red Hat Enterprise Linux Workstation release 6.6 (Santiago)
$> $ python -V
Python 2.6.6
```
#### Virtualenv 13.1.0(latest)

```
$> wget -O- https://github.com/pypa/virtualenv/archive/13.1.0.tar.gz | tar xzvf -
$> python virtualenv-13.1.0/virtualenv.py venv
$> . venv/bin/activate
$> pip install cutadapt
Collecting cutadapt
  Using cached cutadapt-1.8.1.tar.gz
    Complete output from command python setup.py egg_info:
    At least one C source file is missing or out of date.
    ERROR: Cython is not installed. Install at least Cython version 0.17 to continue.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-9HbQAL/cutadapt
```
#### Virtualenv 13.0.0

```
$> deactivate
$> rm -rf venv
$> wget -O- https://github.com/pypa/virtualenv/archive/13.0.0.tar.gz | tar xzvf -
$> python virtualenv-13.0.0/virtualenv.py venv
$> . venv/bin/activate
$>  pip install cutadapt
You are using pip version 7.0.0, however version 7.1.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting cutadapt
  Using cached cutadapt-1.8.1.tar.gz
Building wheels for collected packages: cutadapt
  Running setup.py bdist_wheel for cutadapt
  Stored in directory: /home/username/.cache/pip/wheels/f1/69/b6/bdfd38a0d90b1fd0cdfcd74f6111102469bd9a872137ebc726
Successfully built cutadapt
Installing collected packages: cutadapt
Successfully installed cutadapt-1.8.1
```

**Comment by marcelm** [comment] 2015-07-24 17:38
Thanks a lot! This seems to be indirectly caused by a [setuptools 18.0 changing how Cython files are handled](https://bitbucket.org/pypa/setuptools/issues/288) (virtualenv upgraded the bundled setuptools in version 13.1). I thought at first that their change itself is backwards incompatible, but it seems to be the case that it just triggers a bug in my code which has gone unnoticed so far.

I believe to have fixed the problem: I was checking file modification times to see whether any of the Cython-generated files were out of date, but pip does not preserve modification times when it unpacks the tarball.

Please tell me if you need a fixed tarball. Otherwise, this will be part of the next release.

**Closed** 2015-07-24 17:38 UTC

**Comment by necrolyte2** [comment] 2015-07-24 17:46
No problem, glad it was an easy fix.
We can wait until the next release.
