### ISSUE TITLE
cutadapt: error: Line 3 in FASTQ file is expected to start with '+', but found '@A00208:13' Cutadapt terminated with exit signal: '256'.

### ISSUE THREAD

**Issue by Shicheng-Guo** [marcelm/cutadapt#321] opened 2018-07-24 20:13 UTC
This is cutadapt 1.16 with Python 3.6.5 installed by conda 

Command: 
trim_galore --paired --phred33 --clip_R1 2 --clip_R2 2 --fastqc --illumina Pool_B-plasma_S2_L001_R1_001.fastq.gz Pool_B-plasma_S2_L001_R2_001.fastq.gz --output_dir ../fastq_trim

Result: 
This is cutadapt 1.16 with Python 3.6.5
Command line parameters: -f fastq -e 0.1 -q 20 -O 1 -a AGATCGGAAGAGC Pool_B-tissue_S5_L002_R1_001.fastq.gz
Running on 1 core
Trimming 1 adapter with at most 10.0% errors in single-end mode ...
cutadapt: error: Line 3 in FASTQ file is expected to start with '+', but found '@A00208:13'
Cutadapt terminated with exit signal: '256'.
Terminating Trim Galore run, please check error message(s) to get an idea what went wrong...

I don't think there is problem for my fastq.gz file. 

Thanks. 

Any suggestion.

**Comment by marcelm** [comment] 2018-07-24 20:21
Hi, thanks for reporting. I cannot help with running Trim Galore. Can you try to reproduce the problem with Cutadapt only? If you still see the problem, please report back here. If not, you need to talk to the Trim Galore developers.

Also, please run `zcat Pool_B-plasma_S2_L001_R2_001.fastq.gz | head -n 4`. This will give you the first four lines of your FASTQ file. Unless you are working with sensitive data, please post that here.

**Comment by marcelm** [comment] 2018-07-24 20:30
Looks ok. What does `cutadapt -o /dev/null Pool_B-tissue_S5_L002_R1_001.fastq.gz` give you?

**Comment by Shicheng-Guo** [comment] 2018-07-24 20:38
I think maybe you are right. It is not the bug of cutadapt. maybe trim_galore's problem. I run the adapt command to these two files and till now everything seems okay. 

cutadapt -o ./test/Pool_B-tissue_S5_L002_R1_001.fastq.gz -p ./test/Pool_B-tissue_S5_L002_R2_001.fastq.gz  Pool_B-tissue_S5_L002_R1_001.fastq.gz Pool_B-tissue_S5_L002_R2_001.fastq.gz

**Comment by Shicheng-Guo** [comment] 2018-07-24 20:39
cutadapt -o /dev/null Pool_B-tissue_S5_L002_R1_001.fastq.gz  looks okay. 

I run this code for 10 minutes and everything look good. 

 cutadapt -o /dev/null Pool_B-tissue_S5_L002_R1_001.fastq.gz
This is cutadapt 1.16 with Python 3.6.5
Command line parameters: -o /dev/null Pool_B-tissue_S5_L002_R1_001.fastq.gz
Running on 1 core
Trimming 0 adapters with at most 10.0% errors in single-end mode ...

**Comment by Shicheng-Guo** [comment] 2018-07-24 20:50
Yes. I think it should be trim_galore's fault. in the first step, trim_galore check the read qulity and rewrite a new fastq. there must be something wrong in this step. 

Let me try to update the lastest trim_galore.

**Comment by marcelm** [comment] 2018-07-24 20:59
Thanks for trying this. Let me know how it goes and please close this issue if Cutadapt indeed finishes successfully - and the problem turns out to be in Trim Galore.

**Closed** 2018-08-16 13:02 UTC
