### ISSUE TITLE
error: Reads are improperly paired. while the reads are properly paired

### ISSUE THREAD

**Issue by ranijames** [marcelm/cutadapt#199] opened 2016-05-12 09:41 UTC
Hello All,

I have downloaded file from SRA which I converted into fastq files using fastq-dump.
Now when I try to remove the adapter sequences using cut-adapt. it's throwing me following error,

cutadapt: error: Reads are improperly paired. Read name 'SRR2040271.1.1 SN603_WBP007_8_1101_63.30_99.90 length=100' in file 1 does not match 'SRR2040271.1.2 SN603_WBP007_8_1101_63.30_99.90 length=100' in file 2.

For me, both fastq files have properly paired reads.

file_1.fastq,

@SRR2040271.1.1 SN603_WBP007_8_1101_63.30_99.90 length=100
NTCATTCCATGACATTGTCTGTTGGTTGCTTTTTGAGTATATTTTCTCATGGCTTCATCTATCTTGCTCATAAGACTAAATGGGGAGACAGACTTCCTGG
+SRR2040271.1.1 SN603_WBP007_8_1101_63.30_99.90 length=100
!1=DDFFFGHHHHIJJJJJIIJJJGGHJGJIJJGBGGHEGHJIIIIEHIJEH>@G;FHCG<<BCG:CG@F4@D@=@DG>EE>EED(,,(;((,;;@A>CC

and file_2.fastq,
@SRR2040271.1.2 SN603_WBP007_8_1101_63.30_99.90 length=100
AGACTTCAGACTACCACAGAGCCCACACAGCCAGGAAGTCTGTCTCCCCATTTAGTCTTATGAGCAAGATAGATGAAGCCATGAGAAAATATACTCAAAA
+SRR2040271.1.2 SN603_WBP007_8_1101_63.30_99.90 length=100
CCCFFFFFHHHGHJIIJIIIJJJIIJJJIJIJGIIJJJHIIJHIJIJJJJIJJJIHGIJJJJIIIGIIJHGHHHHFEEEECEEECEDDCCCDEEEDDDCD

**Comment by marcelm** [comment] 2016-05-13 13:58
This is a duplicate of issue #197.

Only the part before the first whitespace is considered the "read name" by cutadapt. The names therefore are:
```
SRR2040271.1.1
```
and
```
SRR2040271.1.2
```
Cutadapt requires that read names are identical. The only difference allowed between read names is that one of them may end in `/1` and the other in `/2`. Which tool did you use to convert the reads from SRA format to FASTQ? `fastq-dump --split-files SRR2040271` does *not* append the `.1`/`.2`, at least in the version I have.

Since you are the second person reporting such an issue, I am considering relaxing the check in cutadapt. However, even if cutadapt were to ignore this, then the next tool (probably your read mapper) will complain, so you haven’t gained anything. I still recommend fixing the read names.

**Comment by marcelm** [comment] 2016-05-13 14:11
I overlooked that you use `fastq-dump`. Which version is that? I use 2.3.5.

**Comment by ranijames** [comment] 2016-05-13 15:04
Hello I have used fastq dump 2.3.4 version and following is my command line,

`fastq-dump.2.3.4 -I --split-3 SRR2040271.sra`

**Comment by marcelm** [comment] 2016-05-19 11:42
Ah, ok, it seems the `-I` option is adding the extra `.1` and `.2`. Please omit that option for now and re-run `fastq-dump`. You can also wait for the next cutadapt version 1.10, which I will release soon and which will not flag these files as improperly paired anymore.

**Closed** 2016-05-19 12:11 UTC

**Comment by arteymix** [comment] 2021-08-12 23:09
I'm having this issue with cutadapt 2.10. @marcelm Has it been resolved at all in 1.10?
