### ISSUE TITLE
No reads processed when trimming paired-end reads after reads shortening

### ISSUE THREAD

**Issue by lynnyummy** [marcelm/cutadapt#488] opened 2020-11-01 03:57 UTC
Hi, I am using Cutadapt to shorten the PE 150 bp reads to 75 bp by using the `-l` parameter. And after I shortened the reads I continued to remove the adaptors by using `-a` and `-A` for the pair-end reads. But it reported the error of `No reads processed`.  I tried to remove the adaptors by using the original 150 bp reads, it works, so I confused why it can not work with the shorten 75 bp reads?

- Cutadapt and Python version
cutadapt 2.5 with Python 3.6.10

- How you installed the tool (conda or pip, for example)
installed this tool via conda

- Which command-line parameters you used
For the read shortening, I used
 `cutadapt -l 75 my_150_1.fq.gz > my_75_1.fq.gz`
`cutadapt -l 75 my_150_2.fq.gz > my_75_2.fq.gz`
For the trimming paired-end reads, I used
`cutadapt -a adaptor1 -A adaptor2 -o my_75_1_trim.fq.gz -p my_75_2_trim.fq.gz my_75_1.fq.gz my_75_2.fq.gz`

Would you please help to solve this issue? Thank you very much!

**Comment by marcelm** [comment] 2020-11-02 09:12
> `cutadapt -l 75 my_150_1.fq.gz > my_75_1.fq.gz`

This command won’t work as intended because the output from stdout is uncompressed, but you’re sending it to a file that has the file name extension `.gz`. To write compressed output, use
```
cutadapt -l 75 -o my_75_1.fq.gz my_150_1.fq.gz
```
which allows Cutadapt to see the output file name and enable compression automatically. Alternatively, pipe output through `gzip`:
```
cutadapt -l 75 my_150_1.fq.gz | gzip > my_75_1.fq.gz
```

**Comment by lynnyummy** [comment] 2020-11-05 10:01
> > `cutadapt -l 75 my_150_1.fq.gz > my_75_1.fq.gz`
> 
> This command won’t work as intended because the output from stdout is uncompressed, but you’re sending it to a file that has the file name extension `.gz`. To write compressed output, use
> 
> ```
> cutadapt -l 75 -o my_75_1.fq.gz my_150_1.fq.gz
> ```
> 
> which allows Cutadapt to see the output file name and enable compression automatically. Alternatively, pipe output through `gzip`:
> 
> ```
> cutadapt -l 75 my_150_1.fq.gz | gzip > my_75_1.fq.gz
> ```

Hi Marcel,

Thanks for your reply! Sorry for my late response, I tried to trim the adaptors first and them cut them into 75 bp length, though in .gz file, it also works!  
Next time I would try to `gzip` the file if I meet this issue again, thank you very much for your help!

**Comment by marcelm** [comment] 2020-11-05 19:31
Great, I’m closing this issue then.

**Closed by marcelm** 2020-11-05 19:31 UTC
