### ISSUE TITLE
Demultiplexer may cause `OSError: [Errno 24] Too many open files` on large sample runs

### ISSUE THREAD

**Issue by jakereps** [marcelm/cutadapt#320] opened 2018-07-22 23:41 UTC
On large sample count runs (or possibly smaller if the system itself is using a large amount of files at the time of analysis), any pipeline using the `Demultiplixer` class may run into an operating system error due to having too many open file descriptors. 

This was brought up by a user on the [QIIME 2 forum](https://forum.qiime2.org/t/plug-in-error-from-cutadat/3417) and appears to be identical to the issue [that the initial `qiime2/q2-demux` implementation was facing](https://github.com/qiime2/q2-demux/issues/19) that was [fixed here](https://github.com/qiime2/q2-demux/commit/974269272af26b4345fc9c97ae5eb2895ce3b833).

The way it was solved on QIIME 2's demultiplexer was by randomly closing X% of the sample files to keep it below the system limit. I would gladly lend a hand in adding a patch and opening a pull request into `cutadapt` if you would like.

This issue pertains to any version of `cutadapt` that uses [these lines](https://github.com/marcelm/cutadapt/blob/1be48f1e146a2f900f08b9fdde2a7c3475e74395/src/cutadapt/filters.py#L235-L236).

**Comment by marcelm** [comment] 2018-07-24 20:50
Good point, thanks for noticing. I’d of course be happy about a patch. One problem though is that the `seqio.open` function doesn’t support `mode='a'` at the moment, so that will also need to be implemented. 

I’ve started to rewrite the FASTA/FASTQ parsers and writers (code that was previously in the seqio module) to make them more efficient and moved them to a separate project (https://github.com/marcelm/dnaio/). Either you submit a PR there as well to add an append option, or you wait for me to do this when I’m back to work around middle of August.

**Comment by marcelm** [comment] 2019-09-02 08:07
I’m wondering how to solve this. Closing some of the files and re-opening them when nceessary sounds like it should work, but then I wonder how to actually do this when working with compressed output. For gzip files, we would get a multipart gzip in the end. It’s probably not easily possible to just close the underlying file descriptor and re-attach a new one later.

However, one thought just crossed my mind: If the problematic limit is a soft limit, we could just raise it ourselves with `resource.setrlimit()`. Then the problem would only arise when we hit the hard limit.

**Comment by marcelm** [comment] 2019-09-04 09:25
I’ve now changed the demultiplexer such that it will raise the soft limit if it gets the "Too many open files" error.

**Comment by fasterius** [comment] 2019-09-04 09:26
Okay, cool, thanks for fixing it!

**Comment by peterjc** [comment] 2020-03-30 20:02
Is this known to work on macOS with cutadapt v2.9?

I just had it fail having made 251 output files (900 expected, plus any unknowns), suggesting that increasing the soft limit did not work since it started at 256:

```
$ python -c "import resource; print(resource.getrlimit(resource.RLIMIT_NOFILE))"
(256, 9223372036854775807)
```

I seem to have the latest version of cutadapt and dnaio installed:

```
$ cutadapt --version
2.9
$ python -c "import cutadapt; print(cutadapt.__version__)"
2.9
$ python -c "import dnaio; print(dnaio.__version__)"
0.4.1
```

Increasing the limit directly seems to work:

```
python -c "import resource; soft, hard = resource.getrlimit(resource.RLIMIT_NOFILE); resource.setrlimit(resource.RLIMIT_NOFILE, (max(soft, 1000), hard)); print(resource.getrlimit(resource.RLIMIT_NOFILE))"
(1000, 9223372036854775807)
```

Workaround, I inserted this into ``cutadapt/utils.py`` after the imports:

```python
def hackery(minimum):
    """Max files hack."""
    import resource
    soft, hard = resource.getrlimit(resource.RLIMIT_NOFILE)
    if soft < minimum:
        resource.setrlimit(resource.RLIMIT_NOFILE, (minimum, hard))

hackery(1000)
```

**Comment by marcelm** [comment] 2020-03-30 21:53
I’m on Linux, so possibly this doesn’t work as intended on macOS.

The limit is only raised when, upon opening a file, an `OSError` is raised and the `errno` is `errno.EMFILE` in the [open_raise_limit function](https://github.com/marcelm/cutadapt/blob/3bb88a2ca0868ba5eca7d272d6976b96d5e4d0f9/src/cutadapt/utils.py#L188). If the raised error or error code is different on macOS, this will not work.

Can you run this and let me know which output you get?
```
python3 -c '[open("deleteme-" + str(i), "w") for i in range(1000)]'
```
On Linux, I see this:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <listcomp>
OSError: [Errno 24] Too many open files: 'deleteme-1021'
```

**Comment by peterjc** [comment] 2020-03-30 21:59
On macOS using Python via conda:

```
$ python3 --version
Python 3.7.6
$ python3 -c '[open("deleteme-" + str(i), "w") for i in range(1000)]'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <listcomp>
OSError: [Errno 24] Too many open files: 'deleteme-253'
```

i.e. Looks like the same exception as on Linux, so while the default is lower, the approach ought to work... strange.

**Comment by marcelm** [comment] 2020-03-30 22:03
Strange indeed. Can you paste the original traceback of the error that you got when you reached the 251 files during demultiplexing? I’d like to know at which point in the code this actually occurs. Perhaps I forgot to use the `open_raise_limit` function in some place.

**Comment by peterjc** [comment] 2020-03-30 22:16
For what it is worth,

```
Traceback (most recent call last):
  File "/Users/xxx/miniconda3/lib/python3.7/site-packages/cutadapt/utils.py", line 184, in dnaio_open_raise_limit
    f = self.dnaio_open(path, mode="w", qualities=qualities)
  File "/Users/xxx/miniconda3/lib/python3.7/site-packages/cutadapt/utils.py", line 176, in dnaio_open
    return dnaio.open(*args, **kwargs)
  File "/Users/xxx/miniconda3/lib/python3.7/site-packages/dnaio/__init__.py", line 109, in open
    file1, opener=opener, fileformat=fileformat, mode=mode, qualities=qualities)
  File "/Users/xxx/miniconda3/lib/python3.7/site-packages/dnaio/__init__.py", line 140, in _open_single
    file = opener(path, mode + "b")
  File "/Users/xxx/miniconda3/lib/python3.7/site-packages/cutadapt/utils.py", line 155, in xopen
    return xopen(path, mode, compresslevel=self.compression_level, threads=self.threads)
  File "/Users/xxx/miniconda3/lib/python3.7/site-packages/xopen/__init__.py", line 410, in xopen
    return open(filename, mode)
OSError: [Errno 24] Too many open files: 'intermediate/XX_XXXX_XXX.fasta'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xxx/miniconda3/bin/cutadapt", line 8, in <module>
    sys.exit(main())
  File "/Users/xxx/miniconda3/lib/python3.7/site-packages/cutadapt/__main__.py", line 868, in main
    stats = r.run()
  File "/Users/xxx/miniconda3/lib/python3.7/site-packages/cutadapt/pipeline.py", line 798, in run
    (n, total1_bp, total2_bp) = self._pipeline.process_reads(progress=self._progress)
  File "/Users/xxx/miniconda3/lib/python3.7/site-packages/cutadapt/pipeline.py", line 287, in process_reads
    if filter_(read, info):
  File "/Users/xxx/miniconda3/lib/python3.7/site-packages/cutadapt/filters.py", line 309, in __call__
    self.template.replace('{name}', name), self.qualities)
  File "/Users/xxx/miniconda3/lib/python3.7/site-packages/cutadapt/utils.py", line 188, in dnaio_open_raise_limit
    f = self.dnaio_open(path, mode="w", qualities=qualities)
  File "/Users/xxx/miniconda3/lib/python3.7/site-packages/cutadapt/utils.py", line 176, in dnaio_open
    return dnaio.open(*args, **kwargs)
  File "/Users/xxx/miniconda3/lib/python3.7/site-packages/dnaio/__init__.py", line 109, in open
    file1, opener=opener, fileformat=fileformat, mode=mode, qualities=qualities)
  File "/Users/xxx/miniconda3/lib/python3.7/site-packages/dnaio/__init__.py", line 140, in _open_single
    file = opener(path, mode + "b")
  File "/Users/xxx/miniconda3/lib/python3.7/site-packages/cutadapt/utils.py", line 155, in xopen
    return xopen(path, mode, compresslevel=self.compression_level, threads=self.threads)
  File "/Users/xxx/miniconda3/lib/python3.7/site-packages/xopen/__init__.py", line 410, in xopen
    return open(filename, mode)
OSError: [Errno 24] Too many open files: 'intermediate/XX_XXXX_XXX.fasta'
```

One of those double-exceptions where Python 3 needs ``raise ... from None`` to avoid.

**Comment by marcelm** [comment] 2020-03-30 22:40
Hm, ok. If I interpret this correctly, the correct function is called, encounters too many files, and after having tried to raise the limit, it still encounters too many files when re-attempting opening the output file. I’ll have to sleep on this ...

**Comment by marcelm** [comment] 2020-03-30 22:52
Ok, one last thing for today: Can you try to raise the limit to 256+8 instead of 1000? This is what the `open_raise_limit` function does. Modifying your code:
```
python -c "import resource; soft, hard = resource.getrlimit(resource.RLIMIT_NOFILE); resource.setrlimit(resource.RLIMIT_NOFILE, (264, hard)); print(resource.getrlimit(resource.RLIMIT_NOFILE))"
```

**Comment by peterjc** [comment] 2020-03-30 22:57
Worth a try, but that works:

```
$ python -c "import resource; soft, hard = resource.getrlimit(resource.RLIMIT_NOFILE); resource.setrlimit(resource.RLIMIT_NOFILE, (264, hard)); print(resource.getrlimit(resource.RLIMIT_NOFILE))"
(264, 9223372036854775807)
```

Maybe one of us will have a bright idea after a sleep. I may be able to dig further into this, but my WFH time availability is rather stochastic right now...

**Comment by marcelm** [comment] 2020-03-31 10:53
Ok, I found it ... the problem actually also occurs on Linux, no idea why I haven’t seen it so far. The `raise_open_files_limit` function, which is called when there are too many open files, has an `import resource`, which – wait for it – *fails* because there are too many open files. Since the import is wrapped in a `try: ... except ImportError: pass` (which was meant to catch the case that this is being run on Windows), it fails silently.

I’ll fix this after lunch.

**Comment by marcelm** [comment] 2020-03-31 13:36
I’ve (hopefully) fixed this now by importing the `resource` module once at the top of the file as one would normally do anyway. I’m also closing this issue now. I had left it open since I had somehow hoped to implement some more sophisticated open-file management so that the too-many-files limit wouldn’t actually be hit in the demultiplexing code, but this is unrealistic at the moment. If anyone still has problems, please comment and I’ll re-open.

@peterjc Thanks for finding this and the great debugging help!

**Comment by peterjc** [comment] 2020-03-31 21:57
Wow - the lazy import itself was failing (because the file handle limit had been reached). Nice job debugging this 👍

**Comment by PeterCronin95** [comment] 2021-03-14 16:49
Hi Marcel, 

I am very new to this line of work. But I am having this same issue. OSError: [Errno 24] Too many open files:

I am using: "This is cutadapt 3.3 with Python 3.8.8". Many thanks in advance.

**Comment by marcelm** [comment] 2021-03-14 20:17
Thanks for reporting. I think that the changes in 9a9ace620151832ea4e3310b67fd572eb602c321 made this re-appear. In case the discussion above was a bit cryptic:
- Each process has two limits, soft and hard, related to how many files it may open simultaneously.
- If the *soft limit* is reached, opening a file gives an error.
- The process may choose to increase the limit up to what is given by the *hard limit*.
- This is what Cutadapt should do if it encounters the "Too many open files" error, but it doesn’t anymore, at least not in all cases.
- 
Can you please check both the soft and hard limits with these commands:
```
ulimit -n
ulimit -H -n
```
The first command gives you the soft limit. If your hard limit is large enough, you should be able to (temporarily) raise the soft limit by issueing something like this:
```
ulimit -n 100
```
If you then re-try the Cutadapt command, it may work.

I will fix this in Cutadapt as well.

**Closed** 2021-03-14 20:25 UTC
Labels: bug

**Comment by marcelm** [comment] 2021-03-14 20:29
I have fixed this again. In my tests, Cutadapt properly attempts to raise the soft limit.

**Comment by PeterCx** [comment] 2021-03-14 21:09
Yes it is working. Brilliant.

Thanks for your help, much appreciated.

**Comment by peterjc** [comment] 2021-03-30 12:47
@LukDrey Right now bioconda's cutadapt is v3.3 which is the latest release: https://anaconda.org/bioconda/cutadapt/files

The recent fix from earlier in March 2021 is in the as yet unreleased development version of cutadapt - install from GitHub if you urgently need it.

**Comment by LukDrey** [comment] 2021-03-30 12:56
Great thank you! I missed that. I can live with the manual workaround. Thanks for the quick reply!

**Comment by marcelm** [comment] 2021-03-30 13:55
Cutadapt 3.4 is now available on PyPI. Will be an hour or so until it’s on Bioconda.

**Comment by BinhongLiu** [comment] 2021-07-05 09:19
Hi, 
Cutadapt 3.4 is installed with miniconda on Linux (conda install -c bioconda cutadapt). I get the same error as described above.


(cutadapt) LDlab@node4:~/HongbinLiu/wulu$ cutadapt -j 0 -e 0.15 --no-indels -g file:barcodes_fwd.fasta -G file:barcodes_rev.fasta -o demultiplexed_1miss/{name1}-{name2}.R1.fastq.gz -p demultiplexed_1miss/{name1}-{name2}.R2.fastq.gz R1_true.fastq R2_true.fastq
This is cutadapt 3.4 with Python 3.9.5
Command line parameters: -j 0 -e 0.15 --no-indels -g file:barcodes_fwd.fasta -G file:barcodes_rev.fasta -o demultiplexed_1miss/{name1}-{name2}.R1.fastq.gz -p demultiplexed_1miss/{name1}-{name2}.R2.fastq.gz R1_true.fastq R2_true.fastq
Building index of 24 adapters ...
Built an index containing 24 strings.
Building index of 24 adapters ...
Built an index containing 24 strings.
Run "cutadapt --help" to see command-line options.
See https://cutadapt.readthedocs.io/ for full documentation.

cutadapt: error: [Errno 24] Too many open files: '/home/LDlab/miniconda3/envs/cutadapt/lib/python3.9/multiprocessing/queues.py'


(cutadapt) LDlab@node4:~/HongbinLiu/wulu$ cutadapt -j 10 -e 0.15 --no-indels -g file:barcodes_fwd.fasta -G file:barcodes_rev.fasta -o demultiplexed_1miss/{name1}-{name2}.R1.fastq.gz -p demultiplexed_1miss/{name1}-{name2}.R2.fastq.gz R1_true.fastq R2_true.fastq
This is cutadapt 3.4 with Python 3.9.5
Command line parameters: -j 10 -e 0.15 --no-indels -g file:barcodes_fwd.fasta -G file:barcodes_rev.fasta -o demultiplexed_1miss/{name1}-{name2}.R1.fastq.gz -p demultiplexed_1miss/{name1}-{name2}.R2.fastq.gz R1_true.fastq R2_true.fastq
Building index of 24 adapters ...
Built an index containing 24 strings.
Building index of 24 adapters ...
Built an index containing 24 strings.
Run "cutadapt --help" to see command-line options.
See https://cutadapt.readthedocs.io/ for full documentation.

cutadapt: error: [Errno 24] Too many open files: '/home/LDlab/miniconda3/envs/cutadapt/lib/python3.9/multiprocessing/queues.py'


(cutadapt) LDlab@node4:~/HongbinLiu/wulu$ ulimit -H -n
1048576
(cutadapt) LDlab@node4:~/HongbinLiu/wulu$ ulimit -S -n
1024

I'm not sure whether this error was caused by the Soft Limit or Hard Limit. 
ps. I have 24 forward adapters and 24 reverse adapters. Could not cutadapt handle so many combines?

Thanks!

**Comment by marcelm** [comment] 2021-07-05 21:44
Can you please run `ulimit -S -n 4096` and try again? For 24 forward and 24 reverse adapters and paired-end data, you need about 25*25*2=1250 file descriptors, plus a couple for communication between each process. Please also add `--debug` to your command-line options.

If that fixed the problem, then Cutadapt was not able to automatically raise the allowed number of open files. Please file a new issue in that case so that we don’t bother the other people subscribed to this issue (you can copy & paste the text from above into the new issue).

**Comment by BinhongLiu** [comment] 2021-07-06 01:39
Yes, it is working. Thanks for your help, much appreciated!

**Comment by marcelm** [comment] 2021-07-06 05:51
No problem!
