### ISSUE TITLE
memory usage of cutadapt

### ISSUE THREAD

**Issue by mariabernard** [marcelm/cutadapt#266] opened 2017-10-25 06:50 UTC
Hi,

I am updating cutadapt in my pipeline, but I found that cutadapt is consuming much more memory than before.
From cutadapt 1.8.3 to cutadapt 1.11 everything is fine.
But after this version, my job fails with a memory error.

So I compare cutadapt 1.11 and the last version cutadapt 1.14 with the memusage command and with the qacct command (report of a job's execution on a SGE scheduler).
I use 8 differents commands (from A to H)  with the 2 versions:

1. cutadapt 1.11

  | qacct mem | qacct maxvmem | memusage heap peak
-- | -- | -- | --
A | 1,989 | 438.391M | 13430910
B | 2,667 | 438.391M | 13430917
C | 0,116 | 438.387M | 13430928
D | 0,263 | 438.383M | 13430944
E | 1,628 | 438.387M | 13430910
F | 1,936 | 438.391M | 13430917
G | 0,22 | 438.391M | 13430928
H | 0,268 | 438.379M | 13430944

2. cutadapt 1.14

  | qacct mem | qacct maxvmem | memusage heap peak
-- | -- | -- | --
A | 104,845 | 13.187G | 14468433
B | 104,357 | 13.187G | 14468440
C | 2,099 | 10.688G | 14468460
D | 8,063 | 13.187G | 14468476
E | 149,329 | 13.188G | 14468442
F | 125,81 | 13.188G | 14468449
G | 29,449 | 13.188G | 14468460
H | 6,132 | 13.187G | 14468476

memusage and qacct are not consistent, so I don't know which one to believe:
- memusage find a small increase of 1 Go
- qacct find that the vmem is drastically increasing from 400M to 13G !

And in fact this is SGE that interrupt my job so I need to believe qacct logs.

Did you change something in term of memory management between cutadapt 1.11 and cutadapt 1.12 that may explain this ?

best regards

Maria

**Comment by marcelm** [comment] 2017-10-25 08:41
Cutadapt should not use much more memory than required by the Python interpreter. It keeps only the current read or read pair in memory, trims it and then writes it out, so anything more than a few hundred MB in total is highly unexpected. I have not knowingly changed anything in cutadapt since 1.11 that would explain this.

To fix this, I need a way to reproduce the problem, so I would need a dataset that I can run myself and that shows the problem.

A few questions that could also help:

- Which command-line are you using?
- Which Python version?
- In the script that you submit to SGE, do you run other processes that could explain the increase in memory usage?
- Can you ssh into one of the cluster nodes while it is executing your job and check with `top` whether the memory usage of the Python processes that runs cutadapt is actually the one that is responsible for the high memory usage?
- Could you try the above experiment also with cutadapt versions 1.12 and 1.13? Then we can pinpoint at which exact version the problem first appears (if you can make test data available, then I don’t need this).
- If you feed cutadapt with only part of the dataset (let’s say only the first 50% of the reads), does the memory usage decrease?

**Comment by marcelm** [comment] 2017-11-02 19:53
Closing for now because I cannot reproduce. Feel free to reopen or comment with more info if the issue is still relevant.

**Closed by marcelm** 2017-11-02 19:53 UTC
