### ISSUE TITLE
N wildcards should not be counted when computing the error rate

### ISSUE THREAD

**Issue by marcelm** [marcelm/cutadapt#360] opened 2019-02-26 13:21 UTC
In a match of an adapter containing `N` wildcards against the read, the wildcards should not contribute to the length. For example, if adapter `CCNCCC` is matched to `CCTCAC` then the error rate should be computed as 1/5=0.2 because there is one mismatch in five non-N bases.

Otherwise, adapter sequences such as `ACGTN{20}` have an unexpectedly high number of allowed errors.

**Comment by chucknordy** [comment] 2021-08-23 23:38
Hi - I think there may yet be a lingering minor issue here, not with the actual trimming, but with the **"max.err" column** of the output report, at least as of cutadapt version 2.10 (but nothing in the current changelog appears to indicate that this has been addressed in later versions).

The issue is that, while the error rate is computed as advertised (i.e., ignoring N's in the adapter sequence), the value reported in each line of the "max.err" column seems to still be based on the full sequence length, including N's.  So, it's really only a cosmetic issue with the report, but one that could cause confusion... at least it did for me, for awhile!

As a concrete example, here is the report for the trimming of a single 5' adapter, which has a length of 46 bases, including 12 N's at its 3' end -- note that while the "number of allowed errors" is correctly indicated to go no higher than 3, and (in the final "error counts" column) there are no trimming events indicated that had more than 3 errors, the "max.err" column lists values of up to 4 (for L>=40), as if the sequence was in fact a complex 46-mer, rather than a 34-mer plus 12 N's:
```
This is cutadapt 2.10 with Python 3.7.3
Command line parameters: -G AGACGCGTGAGTGGGTTACGTTACATCGAACTGGN{12} -j 32 -e 0.10 -O 22 --info-file=Sample_1C3_4a_Alt/cutdemux/BC_rc-RBP-2020-03-R2/info.txt -o Sample_1
...
=== Second read: Adapter 1 ===

Sequence: AGACGCGTGAGTGGGTTACGTTACATCGAACTGGNNNNNNNNNNNN; Type: regular 5'; Length: 46; Trimmed: 12288651 times

No. of allowed errors:
0-9 bp: 0; 10-19 bp: 1; 20-29 bp: 2; 30-34 bp: 3

Overview of removed sequences
length  count   expect  max.err error counts
20      2300    0.0     2       0 0 2300
21      20928   0.0     2       0 9895 11033
22      286757  0.0     2       215515 46700 24542
23      281522  0.0     2       206346 56061 19115
24      48990   0.0     2       6180 26680 16130
25      33146   0.0     2       8368 2821 21957
26      124167  0.0     2       11136 75592 37439
27      1915309 0.0     2       1519311 315383 80533 82
28      322310  0.0     2       116769 156036 48725 780
29      101442  0.0     2       20152 20256 55494 5540
30      71294   0.0     3       25266 14312 19445 12271
31      328168  0.0     3       174930 93046 36612 23580
32      1357079 0.0     3       1034531 231170 61398 29980
33      801732  0.0     3       515347 195925 60969 29491
34      388929  0.0     3       208715 88709 60332 31173
35      99867   0.0     3       6796 27936 27405 37730
36      211863  0.0     3       137371 35621 17519 21352
37      128057  0.0     3       66828 33763 13335 14131
38      186069  0.0     3       100738 41434 23067 20830
39      355060  0.0     3       200384 78333 45882 30461
40      701191  0.0     4       382894 194539 73127 50631
41      2288999 0.0     4       1710297 392828 122757 63117
42      426278  0.0     4       52858 228634 89848 54938
43      1529849 0.0     4       1102037 240214 122296 65302
44      184119  0.0     4       114 95713 32276 56016
45      55101   0.0     4       1302 734 35719 17346
46      31088   0.0     4       4451 1223 375 25039
47      962     0.0     4       159 474 205 124
48      677     0.0     4       243 104 185 145
49      429     0.0     4       164 85 40 140
50      210     0.0     4       86 57 29 38
51      276     0.0     4       155 51 37 33
52      157     0.0     4       68 34 25 30
53      226     0.0     4       113 48 30 35
```

**Comment by marcelm** [comment] 2021-08-24 11:08
You’re correct, thanks for reporting!

**Comment by marcelm** [comment] 2021-09-07 14:47
Should now be fixed.

**Closed** 2021-09-07 14:47 UTC
