### ISSUE TITLE
Cutadapt errors 

### ISSUE THREAD

**Issue by francesca-guana** [marcelm/cutadapt#446] opened 2020-03-04 13:00 UTC
Dear developer,

I'm using Cutadapt 2.8 on Python 3.5.2 
I installed the tool using python3 -m pip install cutadapt, because pip3 didn't work.

Giving the command line:

cutadapt  -q 28 -m 25 -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCA -A AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT -o s845_1_trimmed.fq.gz -p s845_2_trimmed.fq.gz s845_1.fq.gz s845_2.fq.gz 

I have different error messages every time I run it (here some examples):
UnicodeEncodeError: 'ascii' codec can't encode character '\xc1' in position 31: ordinal not in range(128)

UnicodeEncodeError: 'ascii' codec can't encode character '\xc3' in position 19: ordinal not in range(128)

cutadapt: error: Error in sequence file at unknown line: Reads are improperly paired. Read name 'K00124:167:HJ3KWBBXX:8:1107:15737:6081 1:N:0:AACGTGAT' in file 1 does not match 'K00124:167:HJ³KWBBXX:8:1107:15737:6081 2:N:0:AACGTGAT' in file 2.

Any ideas to solve the problem?

Many thanks
Francesca

**Comment by marcelm** [comment] 2020-03-04 14:23
I’m guessing that there’s something wrong with the input file. Can you run these commands and let me know which error messages you get?
```
cutadapt -o /dev/null s845_1.fq.gz
```
and
```
cutadapt -o /dev/null s845_2.fq.gz
```

**Comment by francesca-guana** [comment] 2020-03-04 14:48
I run the command for the first file and no errors are given.

Finished in 402.13 s (7 us/read; 9.10 M reads/minute).

=== Summary ===

Total reads processed:              60,988,622
Reads with adapters:                         0 (0.0%)
Reads written (passing filters):    60,988,622 (100.0%)

Total basepairs processed: 9,148,293,300 bp
Total written (filtered):  9,148,293,300 bp (100.0%)

**Comment by francesca-guana** [comment] 2020-03-04 15:01
This is th result for the second file.

`Finished in 424.49 s (7 us/read; 8.62 M reads/minute).

=== Summary ===

Total reads processed:              60,988,622
Reads with adapters:                         0 (0.0%)
Reads written (passing filters):    60,988,622 (100.0%)

Total basepairs processed: 9,148,293,300 bp
Total written (filtered):  9,148,293,300 bp (100.0%)
`

**Comment by marcelm** [comment] 2020-03-04 22:39
Hm, weird. This could actually be a hardware problem.

> I have different error messages every time I run it

Do you mean that you actually get different error messages every time you run the exact same command? That should really not happen. If it’s a problem in Cutadapt and the input is identical (and you’re running on a single core, which you do according to your command line), it should always fail at the same position.

> cutadapt: error: Error in sequence file at unknown line: Reads are improperly paired. Read name 'K00124:167:HJ3KWBBXX:8:1107:15737:6081 1:N:0:AACGTGAT' in file 1 does not match 'K00124:167:HJ³KWBBXX:8:1107:15737:6081 2:N:0:AACGTGAT' in file 2.

The difference between the read names is peculiar: The `3` in file 1 is a `³` in file 2. This is another sign for a hardware problem because the bit patterns for `3` and `³` differ in only one position (00110011 vs 10110011, using latin-1). Or do you suppose there could have been a mistake while you copied the text into the GitHub form?

Are you having other (weird) problems on your computer? Then I would think that this is actually a hardware issue.

If not, can you please try the following commands one by one and let me know at which point you start to see failures (you can stop as soon as one of these commands fails):
```
cutadapt -o s845_1_trimmed.fq.gz s845_1.fq.gz
cutadapt -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCA -o s845_1_trimmed.fq.gz s845_1.fq.gz
cutadapt -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCA -A AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT -o s845_1_trimmed.fq.gz -p s845_2_trimmed.fq.gz s845_1.fq.gz s845_2.fq.gz
cutadapt -m 25 -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCA -A AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT -o s845_1_trimmed.fq.gz -p s845_2_trimmed.fq.gz s845_1.fq.gz s845_2.fq.gz
```
The idea is to incrementally transform the `cutadapt -o /dev/null s845_1.fq.gz` command (which you confirmed working) into the original command in order to see which of the options causes the failure.

**Comment by francesca-guana** [comment] 2020-03-05 12:33
I hope that it's not an hardware problem. It not seem to present other problems.

Anyway, I try to follow your suggestion.
First of all, I notice that unicode encode errors are given when I use the option for multiple cores (-j 2). So I decided not to use it, but time of execution really rise up.

No errors are given when I run the command
cutadapt -o s845_1_trimmed.fq.gz s845_1.fq.gz

cutadapt -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCA -o s845_1_trimmed2.fq.gz s845_1.fq.gz

00:52:59    60,910,000 reads  @     58.5 µs/read;   1.03 M reads/
minutecutadapt: error: Error in FASTQ file at line 243712643: Line expected to start with '+', but found '<'

A trimmed file is generated, dimension 5.1 Gb starting from 5.5 Gb

cutadapt -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCA -A AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT -o s845_1_trimmed3.fq.gz -p s845_2_trimmed3.fq.gz s845_1.fq.gz s845_2.fq.gz

00:56:00    28,710,000 reads  @    127.8 µs/read;   0.47 M reads/minutecutadapt: error: Error in FASTQ file at line 114854048: Length of sequence and qualities differ

No trimmed file generated.

What do you think about?

Many thanks

**Comment by marcelm** [comment] 2020-03-05 12:49
Hi, you haven’t replied to this question that I had:

>> I have different error messages every time I run it

> Do you mean that you actually get different error messages every time you run the exact same command?

It would be important to know whether you get different messages or always the same (when running the same command).

**Comment by francesca-guana** [comment] 2020-03-09 08:44
Hi Marcel, 
different errors came running on the same .fq.gz file, command with different options, for example -j or -n options.

**Comment by marcelm** [comment] 2020-03-09 10:39
Ok, but just to clarify: Do you get different messages *when running the exact same command* multiple times?

**Comment by francesca-guana** [comment] 2020-03-09 13:12
I'm sorry if I'm not very accurate in this moment, I've lost the history of the commands I ran so I'm not sure if the errors I mentioned came from exactly the same command or  if I changed some options.

**Comment by francesca-guana** [comment] 2020-03-10 09:31
Yesterday I ran this command two times on the same file and the result was:

cutadapt -q 28 -m 25 -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCA -A AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT -o s1128_1_trimmed.fq.gz -p s1128_2_trimmed.fq.gz s1128_1.fq.gz s1128_2.fq.gz 

01:02:53    36,340,000 reads  @    101.6 µs/read;   0.59 M reads/minute cutadapt: error: Error in sequence file at unknown line: Reads are improperly paired. Read name 'K00124:206:HJHWKBBXX:6:2128:11941:10687 1:N:0:AGTGGTCA' in file 1 does not match 'K00124:206:HJHWKBBXX:6:2128:11941:00687 2:N:0:AGTGGTCA' in file 2.

00:26:54    15,430,000 reads  @    110.0 µs/read;   0.55 M reads/minute cutadapt: error: Error in sequence file at unknown line: Reads are improperly paired. Read name 'K00124:206:HJHWKBBXX:6:1208:2644:12163!1:N:0:AGTGGTCA' in file 1 does not match 'K00124:206:HJHWKBBXX:6:1208:2644:12163 2:N:0:AGTGGTCA' in file 2.

**Comment by francesca-guana** [comment] 2020-03-10 10:59
This is another test I've just made.

cutadapt -q 28 -m 25 -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCA -A AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT -o s1128_1_trimmed.fq.gz -p s1128_2_trimmed.fq.gz s1128_1.fq.gz s1128_2.fq.gz 
This is cutadapt 2.8 with Python 3.5.2

00:35:53    21,830,000 reads  @     90.3 µs/read;   0.66 M reads/minute cutadapt: error: Error in FASTQ file at line 87369347: Line expected to start with '+', but found 'C'

00:01:01       590,000 reads  @    103.9 µs/read;   0.58 M reads/minute cutadapt: error: Error in sequence file at unknown line: Reads are improperly paired. Read name 'K00124:206:HJHWKBBXX:6:1102:14682:19459 1:N:0:AGTGGTCA' in file 1 does not match 'K00124:206:HJHWKBBXX:6:1102:14692:19459 2:N:0:AGTGGTCA' in file 2.

**Comment by marcelm** [comment] 2020-03-10 14:18
Thanks, this is valuable information. So something goes wrong when reading the input file, and where the error occurs is not deterministic.

Cutadapt uses `pigz` (if it is installed) to decompress `.fastq.gz` input files, perhaps the problem is there. Can you please run the following command and let me know what the output is:
```
pigz --version
```
I want to know whether `pigz` is installed, that is, whether you get a "command not found error" or a version number.

If pigz is installed, please use it to decompress one of the input files in the following way:
```
pigz -dc -p1 s1128_1.fq.gz | md5sum
```
This will print a checksum of the uncompressed contents of the file. This will take a couple of minutes on that big input file. However, please run this command a couple of times. Is the checksum the same every time?

If the checksum is *not* the same every time, then `pigz` is somehow broken. In that case, you can force Cutadapt to not use pigz by running it in the following way:
```
PATH= cutadapt -q 28 -m 25 -a ...
```
That is, add `PATH= ` to the beginning of your command (don’t forget the space after the equals sign).

**Comment by francesca-guana** [comment] 2020-03-10 15:43
The result of the command 

pigz -dc -p1 s1128_1.fq.gz | md5sum

is both times the same:

be4c0429801159d3ad058a314be122ee  -

**Comment by marcelm** [comment] 2020-03-11 18:06
Hm. I believe that figuring out where the actual problem is could take a lot of back and forth, and I don’t know how much time you’re ready to invest.

My suggestion is that you first try the `PATH= ` thing that I described above. Then, if that doesn’t work, try to install Cutadapt using Conda. See the [installation instructions](https://cutadapt.readthedocs.io/en/latest/installation.html#installation-with-conda) for this. If you plan to use other bioinformatics tools, I highly recommend using Conda anyway because so much software is available through the bioconda channel.

**Comment by marcelm** [comment] 2020-03-20 09:34
I’m going to close this issue soon if there’s no further feedback. I hope you got it to work.

**Comment by francesca-guana** [comment] 2020-03-20 09:59
I had some problems in working at home, sorry.
Now I'm working with another workstation and it seems ok. Thank you for your help

**Comment by marcelm** [comment] 2020-03-21 10:55
Ok, good to hear!

**Closed by marcelm** 2020-03-21 10:55 UTC
