### ISSUE TITLE
Trim "Primer + upstream attached barcode"

### ISSUE THREAD

**Issue by Emily072020** [marcelm/cutadapt#489] opened 2020-11-02 14:30 UTC
Hi,

Thanks first. This is how I installed and used cutdadapt, followed by my question at the end:

---- How cutadapt is installed:
In my system, I have python2 and python3. Python3 is used to install cutadapt
`python3 -m pip install --user --upgrade cutadapt`

---- cutadapt --version
`2.10`

---- my input fastq:
I have paired-end sequencing data. 
Each paired-end sequence:
R1:
barcode (unfixed length) + 18bp Primer_R1 + target_read_R1
R2:
barcode (unfixed length) + 18bp Primer_R2 + target_read_R2

While the reads are short, there will be complement of Primer_R1 appended to read_R2 and vice versa.
R1:
barcode (unfixed length) + 18bp Primer_R1 + target_read_R1 + complement of 18bp Primer_R2
R2:
barcode (unfixed length) + 18bp Primer_R2 + target_read_R2 + complement of 18bp Primer_R1

An example for short reads (# the grey parts are the 18bp Primers or their complements):

R1:
ATCACACGCTACCC`GGTAAACACTTGGGCACT`target_read_R1`GATCCCAGCTGTAGTCCG`TGTCGAGCGTATGATC

R2:
TACGCTCGACA`CGGACTACAGCTGGGATC`target_read_R2`AGTGCCCAAGTGTTTACC`GGGTAGCGTGTGATAGATC

---- my purpose:
To remove the Primers (also their complements) and their upstream barcodes and keep only the target_read. While Primer_R1 is not detected in R1, discard this read.

---- my command:
`cutadapt -a ^GGTAAACACTTGGGCACT...GATCCCAGCTGTAGTCCG -A CGGACTACAGCTGGGATC...AGTGCCCAAGTGTTTACC --discard-untrimmed -o out1.R1.fastq.gz -p out2.R2.fastq.gz in1.R1.fastq.gz in2.R2_001.fastq.gz`

**---- my results and question:**
It turned out some reads were trimmed correctly and only the target_reads were left.
However, some reads were discarded, like the read in the example above.

Did I do something wrong? How should I adjust my command if so?

Thanks a lot.

**Comment by marcelm** [comment] 2020-11-02 15:18
The problem appears to be that you specified the forward primer on R1 as being anchored. Try to remove the `^` preceding the sequence (`-a GGTAAACACTTGGGCACT...GATCCCAGCTGTAGTCCG`).

If an adapter is anchored to the 5' end, it is only found if the read starts with that sequence. Since you have a preceding barcode sequence, you should not use anchoring.

I know that Cutadapt currently prints out a warning message about the “missing” `^` in the beginning of the sequence, but that does not apply in your case (I won’t be shown any more in future versions since it could be misleading in cases like these).

**Comment by Emily072020** [comment] 2020-11-03 15:41
Thank you very much for your reply. It was the problem as you said.
Besides this, I want to trim all reads to a specific length, e.g. 125bp. 
Is it correct to use -m and -l (as below)?
`cutadapt -a GGTAAACACTTGGGCACT...GATCCCAGCTGTAGTCCG -A CGGACTACAGCTGGGATC...AGTGCCCAAGTGTTTACC -o out1.R1.fastq.gz -p out2.R2.fastq.gz in1.R1.fastq.gz in2.R2_001.fastq.gz  -m 125 -l 125 --untrimmed-output R.untrimmed.fastq.gz --untrimmed-paired-output R.untrimmed.fastq.gz`
(# the "FILE" of parameters --untrimmed-output and --untrimmed-paired-output is the same file)

**Comment by marcelm** [comment] 2020-11-03 16:55
Great to hear that it works.

Using `-l 125` will trim all reads that are longer than 125 basepairs to a length of 125. Using `-m 125` will then throw away all reads that are shorter than 125 basepairs. If that is what you want, then this is the correct way to use the options, yes.

Sending the `--untrimmed-output` and `--untrimmed-paired-output` to the same file will very likely not work as intended. You won’t get an error message, but the output file will contain the reads in an undefined order and some may be missing. If you want to write the paired-end reads in an interleaved order to a single output file (first R1 of the first read, then R2 of the first read, then R1 of the second read, etc.), then you can add `--interleaved` to your command-line options and it will do that.

**Comment by Emily072020** [comment] 2020-11-03 17:40
Thanks.
If the primers (in -a, -A) are not detected in a sequence, then this sequence should be discarded.
If the reads are longer than 125bp, they should be trimmed to 125bp.
However, If the reads are shorter than 125bp, I want to put them to another file, which I **still need to use afterwards** (to trim them to a uniform 50bp). For this purpose, I think parameters `--too-short-output` and `--too-short-paired-output` should be used and I want to write R1 and R2 to different files.

If I run:
`cutadapt -a GGTAAACACTTGGGCACT...GATCCCAGCTGTAGTCCG -A CGGACTACAGCTGGGATC...AGTGCCCAAGTGTTTACC -o out1.R1.fastq.gz -p out2.R2.fastq.gz in1.R1.fastq.gz in2.R2_001.fastq.gz -m 125 -l 125 --untrimmed-output R.untrimmed.fastq.gz --untrimmed-paired-output R.untrimmed.fastq.gz --interleaved --too-short-output R1.short.fastq.gz --too-short-paired-output R2.short.fastq.gz`
Then the reads shorter than 125 will be written to R1.short.fastq.gz and R2.short.fastq.gz I think. 
Since they don't have adapters (in -a, -A as before) anymore, can I still use cutadapt to trim them to a uniform 50 bp?

**Comment by marcelm** [comment] 2020-11-04 16:48
> If the primers (in `-a, -A`) are not detected in a sequence, then this sequence should be discarded.

You can use `--discard-untrimmed` for that.

> If the reads are longer than 125bp, they should be trimmed to 125bp.

`-l 125` is correct for that.

> However, If the reads are shorter than 125bp, I want to put them to another file, which I **still need to use afterwards** (to trim them to a uniform 50bp). For this purpose, I think parameters `--too-short-output` and `--too-short-paired-output` should be used and I want to write R1 and R2 to different files.

Yes, these are the arguments that are needed.

> If I run:
> `cutadapt -a GGTAAACACTTGGGCACT...GATCCCAGCTGTAGTCCG -A CGGACTACAGCTGGGATC...AGTGCCCAAGTGTTTACC -o out1.R1.fastq.gz -p out2.R2.fastq.gz in1.R1.fastq.gz in2.R2_001.fastq.gz -m 125 -l 125 --untrimmed-output R.untrimmed.fastq.gz --untrimmed-paired-output R.untrimmed.fastq.gz --interleaved --too-short-output R1.short.fastq.gz --too-short-paired-output R2.short.fastq.gz`

If you throw away the `R.untrimmed.fastq.gz` file anyway, just use `--discard-untrimmed` as I said above and leave out the `--untrimmed-output`, `--untrimmed-paired-output` and `--interleaved` options.

> Then the reads shorter than 125 will be written to `R1.short.fastq.gz` and `R2.short.fastq.gz` I think.
> Since they don't have adapters (in `-a, -A` as before) anymore, can I still use cutadapt to trim them to a uniform 50 bp?

You mean in a second step? Yes, Cutadapt can be used without trimming adapters.

**Comment by Emily072020** [comment] 2020-11-16 21:01
Hi, all worked and thanks a lot. For my another project, I have an extra request for trimming, which is to trim off another 8bp following the Primer.

Same example as in the previous message, an extra request is that, for R1, I also need to trim off 8bp after the primer "`GGTAAACACTTGGGCACT`" and 8bp before "`GATCCCAGCTGTAGTCCG`". Since this 8bp sequence is not fixed, I cannot directly combine it with the Primer. Is there a proper parameter available for this purpose? Thanks.

**Comment by marcelm** [comment] 2020-11-16 22:57
You can just add an appropriate number of `N` wildcard characters. These will be trimmed off along with the other bases.

So for R1, you can write `GGTAAACACTTGGGCACTNNNNNNNN` or you can use the abbreviation `N{8}` (equivalent to eight `N`): `GGTAAACACTTGGGCACTN{8}`. Similar for the other primer: `N{8}GATCCCAGCTGTAGTCCG`.

**Comment by Emily072020** [comment] 2020-11-16 23:33
I see. Thanks a lot!!

**Comment by marcelm** [comment] 2021-02-02 10:49
I just noticed this issue is still open. I will close it now. Just let me know if there’s anything else.

**Closed by marcelm** 2021-02-02 10:49 UTC
